# Generated by Django 2.2.18 on 2021-02-18 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sync',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('USERS', 'Users'), ('EVICTIONFREE', 'EvictionFreeNY.org submitted hardship declarations')], max_length=30, unique=True)),
                ('last_synced_at', models.DateTimeField()),
            ],
        ),
    ]
