# Generated by Django 2.2.18 on 2021-02-23 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amplitude', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sync',
            name='kind',
            field=models.CharField(choices=[('USERS', 'Users v1 (deprecated)'), ('USERS_V2', 'Users v2'), ('EVICTIONFREE', 'EvictionFreeNY.org submitted hardship declarations')], max_length=30, unique=True),
        ),
    ]
