# Generated by Django 2.2.18 on 2021-03-25 11:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('amplitude', '0002_auto_20210223_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sync',
            name='kind',
            field=models.CharField(choices=[('USERS', 'Users v1 (deprecated)'), ('USERS_V2', 'Users v2'), ('EVICTIONFREE', 'EvictionFreeNY.org submitted hardship declarations'), ('AMPLITUDE', 'Logged events for Amplitude')], max_length=30, unique=True),
        ),
        migrations.CreateModel(
            name='LoggedEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('kind', models.CharField(choices=[('SAFE_MODE_ENABLE', 'Enable compatibility mode'), ('SAFE_MODE_DISABLE', 'Disable compatibility mode')], max_length=50)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('created_at', 'id'),
            },
        ),
    ]
