# Generated by Django 3.2.13 on 2024-01-17 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amplitude', '0003_logged_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loggedevent',
            name='kind',
            field=models.CharField(choices=[('SAFE_MODE_ENABLE', 'Enable compatibility mode'), ('SAFE_MODE_DISABLE', 'Disable compatibility mode'), ('LATENANTS_LETTER_CREATE', 'LA TAC create letter'), ('LATENANTS_LETTER_SEND', 'LA TAC send letter'), ('LATENANTS_LETTER_DOWNLOAD', 'LA TAC download letter')], max_length=50),
        ),
    ]
