# Generated by Django 2.1.2 on 2018-11-30 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hpaction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadtoken',
            name='errored',
            field=models.BooleanField(default=False),
        ),
    ]
