# Generated by Django 2.1.8 on 2019-05-23 12:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hpaction', '0002_uploadtoken_errored'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeWaiverDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income_frequency', models.CharField(choices=[('WEEKLY', 'Weekly'), ('EVERY_TWO_WEEKS', 'Every two weeks'), ('MONTHLY', 'Monthly')], max_length=50)),
                ('income_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('income_src_employment', models.BooleanField()),
                ('income_src_hra', models.BooleanField()),
                ('income_src_child_support', models.BooleanField()),
                ('income_src_alimony', models.BooleanField()),
                ('rent_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expense_utilities', models.BooleanField()),
                ('expense_cable', models.BooleanField()),
                ('expense_phone', models.BooleanField()),
                ('expense_childcare', models.BooleanField()),
                ('asked_before', models.BooleanField()),
                ('user', models.OneToOneField(help_text='The user whom this fee waiver is for.', on_delete=django.db.models.deletion.CASCADE, related_name='fee_waiver_details', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
