# Generated by Django 2.1.8 on 2019-06-14 15:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hpaction', '0003_feewaiverdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantChild',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text="The child's name.", max_length=80)),
                ('dob', models.DateField(help_text="The child's date of birth.")),
                ('user', models.ForeignKey(help_text='The user who this child belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='children', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
