# Generated by Django 2.1.8 on 2019-06-20 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hpaction', '0007_auto_20190618_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='hpactiondetails',
            name='sue_for_harassment',
            field=models.NullBooleanField(help_text='Whether the user wants to sue for harassment.'),
        ),
    ]
