# Generated by Django 2.1.8 on 2019-06-24 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hpaction', '0009_harassmentdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='harassmentdetails',
            name='alleg_conduct_in_violation',
            field=models.BooleanField(default=False, help_text='Whether the tenant alleges the landlord has CONDUCT_IN_VIOLATION.', verbose_name='Harassment allegation: CONDUCT_IN_VIOLATION'),
        ),
        migrations.AddField(
            model_name='harassmentdetails',
            name='alleg_contact',
            field=models.BooleanField(default=False, help_text='Whether the tenant alleges the landlord has CONTACT.', verbose_name='Harassment allegation: CONTACT'),
        ),
        migrations.AddField(
            model_name='harassmentdetails',
            name='alleg_disturbed',
            field=models.BooleanField(default=False, help_text='Whether the tenant alleges the landlord has DISTURBED.', verbose_name='Harassment allegation: DISTURBED'),
        ),
        migrations.AddField(
            model_name='harassmentdetails',
            name='alleg_failed_to_comply',
            field=models.BooleanField(default=False, help_text='Whether the tenant alleges the landlord has FAILED_TO_COMPLY.', verbose_name='Harassment allegation: FAILED_TO_COMPLY'),
        ),
        migrations.AddField(
            model_name='harassmentdetails',
            name='alleg_false_cert_repairs',
            field=models.BooleanField(default=False, help_text='Whether the tenant alleges the landlord has FALSE_CERT_REPAIRS.', verbose_name='Harassment allegation: FALSE_CERT_REPAIRS'),
        ),
        migrations.AddField(
            model_name='harassmentdetails',
            name='alleg_force',
            field=models.BooleanField(default=False, help_text='Whether the tenant alleges the landlord has FORCE.', verbose_name='Harassment allegation: FORCE'),
        ),
        migrations.AddField(
            model_name='harassmentdetails',
            name='alleg_induced_leaving',
            field=models.BooleanField(default=False, help_text='Whether the tenant alleges the landlord has INDUCED_LEAVING.', verbose_name='Harassment allegation: INDUCED_LEAVING'),
        ),
        migrations.AddField(
            model_name='harassmentdetails',
            name='alleg_misleading_info',
            field=models.BooleanField(default=False, help_text='Whether the tenant alleges the landlord has MISLEADING_INFO.', verbose_name='Harassment allegation: MISLEADING_INFO'),
        ),
        migrations.AddField(
            model_name='harassmentdetails',
            name='alleg_removed_possessions',
            field=models.BooleanField(default=False, help_text='Whether the tenant alleges the landlord has REMOVED_POSSESSIONS.', verbose_name='Harassment allegation: REMOVED_POSSESSIONS'),
        ),
        migrations.AddField(
            model_name='harassmentdetails',
            name='alleg_requested_id',
            field=models.BooleanField(default=False, help_text='Whether the tenant alleges the landlord has REQUESTED_ID.', verbose_name='Harassment allegation: REQUESTED_ID'),
        ),
        migrations.AddField(
            model_name='harassmentdetails',
            name='alleg_stopped_service',
            field=models.BooleanField(default=False, help_text='Whether the tenant alleges the landlord has STOPPED_SERVICE.', verbose_name='Harassment allegation: STOPPED_SERVICE'),
        ),
        migrations.AddField(
            model_name='harassmentdetails',
            name='alleg_sued',
            field=models.BooleanField(default=False, help_text='Whether the tenant alleges the landlord has SUED.', verbose_name='Harassment allegation: SUED'),
        ),
        migrations.AddField(
            model_name='harassmentdetails',
            name='alleg_threats_re_status',
            field=models.BooleanField(default=False, help_text='Whether the tenant alleges the landlord has THREATS_RE_STATUS.', verbose_name='Harassment allegation: THREATS_RE_STATUS'),
        ),
    ]
