# Generated by Django 2.1.8 on 2019-06-24 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hpaction', '0010_add_harassment_allegations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='harassmentdetails',
            name='harassment_details',
            field=models.TextField(blank=True, help_text='Explain how the landlord has harassed you.', max_length=900),
        ),
        migrations.AlterField(
            model_name='harassmentdetails',
            name='prior_relief_sought_case_numbers_and_dates',
            field=models.TextField(blank=True, help_text='\n            Please provide the court case number (the "index number") and/or the date(s)\n            of the earlier case(s).  (Please also include the case number and date(s) of\n            any case(s) you have brought in the housing court for repairs.)\n            ', max_length=250),
        ),
    ]
