# Generated by Django 2.2.2 on 2019-07-02 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hpaction', '0012_hpactiondetails_sue_for_repairs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hpactiondetails',
            name='sue_for_harassment',
            field=models.BooleanField(default=False, help_text='Whether the user wants to sue for harassment.'),
        ),
        migrations.AlterField(
            model_name='hpactiondetails',
            name='sue_for_repairs',
            field=models.BooleanField(default=False, help_text='Whether the user wants to sue for repairs.'),
        ),
    ]
