# Generated by Django 2.2.2 on 2019-07-03 20:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hpaction', '0012_hpactiondetails_sue_for_repairs'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriorCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case_number', models.CharField(help_text='The court case number (also known as the "index number").', max_length=9)),
                ('case_date', models.DateField(help_text='The date of the case.')),
                ('is_harassment', models.BooleanField(help_text='Whether this is a harassment case.')),
                ('is_repairs', models.BooleanField(help_text='Whether this is a repairs case.')),
                ('user', models.ForeignKey(help_text='The user who this prior case belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='prior_hp_action_cases', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
