# Generated by Django 2.2.2 on 2019-07-05 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hpaction', '0013_priorcase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='harassmentdetails',
            name='prior_relief_sought_case_numbers_and_dates',
        ),
    ]
