# Generated by Django 2.2.3 on 2019-07-11 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hpaction', '0014_remove_harassmentdetails_prior_relief_sought_case_numbers_and_dates'),
    ]

    operations = [
        migrations.AddField(
            model_name='harassmentdetails',
            name='two_or_less_apartments_in_building',
            field=models.NullBooleanField(help_text='Does you building have 2 apartments or less?'),
        ),
    ]
