# Generated by Django 2.2.3 on 2019-07-11 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hpaction', '0015_harassmentdetails_two_or_less_apartments_in_building'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='harassmentdetails',
            name='more_than_two_apartments_in_building',
        ),
    ]
