# Generated by Django 2.2.3 on 2019-07-12 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hpaction', '0016_remove_harassmentdetails_more_than_two_apartments_in_building'),
    ]

    operations = [
        migrations.AddField(
            model_name='feewaiverdetails',
            name='income_src_social_security',
            field=models.BooleanField(default=False, help_text='Whether the user receives income from social security.', verbose_name='Social security'),
        ),
    ]
