# Generated by Django 2.2.10 on 2020-03-23 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hpaction', '0017_feewaiverdetails_income_src_social_security'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocusignConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('private_key', models.TextField(blank=True, help_text='The private key for the DocuSign Service Integration.')),
                ('consent_code', models.TextField(blank=True)),
                ('consent_code_updated_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
