# Generated by Django 2.2.10 on 2020-04-03 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hpaction', '0018_auto_20200402_1426'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocusignEnvelope',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In progress'), ('SIGNED', 'Signed'), ('DECLINED', 'Declined')], default='IN_PROGRESS', max_length=30)),
                ('docs', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hpaction.HPActionDocuments')),
            ],
        ),
    ]
