# Generated by Django 2.2.10 on 2020-03-23 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hpaction', '0018_docusignconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='docusignconfig',
            name='base_uri',
            field=models.URLField(blank=True),
        ),
    ]
