# Generated by Django 2.2.10 on 2020-05-02 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hpaction', '0020_config'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hpuser',
            options={'verbose_name': 'User with HP Action', 'verbose_name_plural': 'Users with HP Actions'},
        ),
    ]
