# Generated by Django 2.2.13 on 2020-08-18 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hpaction', '0022_servingpapers'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourtContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="The contact's name.", max_length=100)),
                ('email', models.EmailField(help_text="The contact's email address.", max_length=254)),
                ('court', models.CharField(choices=[('BROOKLYN', 'Brooklyn'), ('QUEENS', 'Queens'), ('BRONX', 'Bronx'), ('MANHATTAN', 'Manhattan'), ('STATEN_ISLAND', 'Staten Island')], help_text="The housing court the contact belongs to. Signed HPs for this court will be sent to this person's email address.", max_length=100)),
            ],
        ),
    ]
