# Generated by Django 2.2.13 on 2020-11-04 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hpaction', '0025_managementcompanydetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managementcompanydetails',
            name='name',
            field=models.CharField(blank=True, help_text="The management company's name.", max_length=40),
        ),
    ]
