# Generated by Django 3.2 on 2021-04-12 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hpaction', '0026_auto_20201104_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feewaiverdetails',
            name='asked_before',
            field=models.BooleanField(blank=True, help_text='Whether the user has requested a fee waiver before.', null=True),
        ),
        migrations.AlterField(
            model_name='feewaiverdetails',
            name='receives_public_assistance',
            field=models.BooleanField(blank=True, help_text='Whether the user receives any kind of public assistance benefits, e.g. cash benefits, rent assistance, food stamps, Medicaid.', null=True),
        ),
        migrations.AlterField(
            model_name='harassmentdetails',
            name='more_than_one_family_per_apartment',
            field=models.BooleanField(blank=True, help_text='Is there more than one family living in each apartment?', null=True),
        ),
        migrations.AlterField(
            model_name='harassmentdetails',
            name='two_or_less_apartments_in_building',
            field=models.BooleanField(blank=True, help_text='Does you building have 2 apartments or less?', null=True),
        ),
        migrations.AlterField(
            model_name='hpactiondetails',
            name='filed_with_311',
            field=models.BooleanField(blank=True, help_text='Whether the user has filed any complaints with 311 before.', null=True),
        ),
        migrations.AlterField(
            model_name='hpactiondetails',
            name='hpd_issued_violations',
            field=models.BooleanField(blank=True, help_text='Whether HPD issued any violations.', null=True),
        ),
        migrations.AlterField(
            model_name='hpactiondetails',
            name='sue_for_harassment',
            field=models.BooleanField(blank=True, help_text='Whether the user wants to sue for harassment.', null=True),
        ),
        migrations.AlterField(
            model_name='hpactiondetails',
            name='sue_for_repairs',
            field=models.BooleanField(blank=True, help_text='Whether the user wants to sue for repairs.', null=True),
        ),
        migrations.AlterField(
            model_name='hpactiondetails',
            name='thirty_days_since_311',
            field=models.BooleanField(blank=True, help_text='Whether 30 days have passed since the user filed complaints with 311.', null=True),
        ),
        migrations.AlterField(
            model_name='hpactiondetails',
            name='thirty_days_since_violations',
            field=models.BooleanField(blank=True, help_text='Whether 30 days have passed since HPD issued violations.', null=True),
        ),
        migrations.AlterField(
            model_name='hpactiondetails',
            name='urgent_and_dangerous',
            field=models.BooleanField(blank=True, help_text='Whether the conditions are urgent and dangerous.', null=True),
        ),
        migrations.AlterField(
            model_name='servingpapers',
            name='lob_letter_object',
            field=models.JSONField(blank=True, help_text='If the papers were sent via Lob, this is the JSON response of the API call that was made to send them, documented at https://lob.com/docs/python#letters.', null=True),
        ),
    ]
