# Generated by Django 2.1 on 2018-09-05 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='justfixuser',
            name='full_name',
            field=models.CharField(blank=True, help_text="The user's full name.", max_length=150, verbose_name='Full name'),
        ),
    ]
