# Generated by Django 2.1 on 2018-09-25 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_justfixuser_full_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='justfixuser',
            name='full_name',
        ),
    ]
