# Generated by Django 2.1.2 on 2018-10-29 12:10

from django.db import migrations
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_justfixuser_full_name'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='justfixuser',
            managers=[
                ('objects', users.models.JustfixUserManager()),
            ],
        ),
    ]
