# Generated by Django 2.1.2 on 2018-12-05 12:11

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20181029_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='justfixuser',
            name='phone_number',
            field=models.CharField(help_text='A U.S. phone number without parentheses or hyphens, e.g. "5551234567".', max_length=10, unique=True, validators=[users.models.validate_phone_number], verbose_name='Phone number'),
        ),
    ]
