# Generated by Django 2.2.10 on 2020-05-20 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_justfixuser_is_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='justfixuser',
            name='locale',
            field=models.CharField(choices=[('en', 'English'), ('es', 'Spanish')], default='en', help_text="The user's preferred locale/language.", max_length=5),
        ),
    ]
