# Generated by Django 2.2.18 on 2021-02-26 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_justfixuser_locale'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='justfixuser',
            options={'permissions': [('download_sandefur_data', "Can download data needed for Rebecca Sandefur's research")]},
        ),
    ]
