# Generated by Django 2.2.18 on 2021-03-05 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_add_sandefur_permission'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='justfixuser',
            options={'permissions': [('impersonate_users', 'Can impersonate other users'), ('download_sandefur_data', "Can download data needed for Rebecca Sandefur's research")], 'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
