# Generated by Django 2.1.5 on 2019-01-24 16:00

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Borough',
            fields=[
                ('code', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, unique=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='CommunityDistrict',
            fields=[
                ('boro_cd', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
            options={
                'ordering': ['boro_cd'],
            },
        ),
        migrations.CreateModel(
            name='Neighborhood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('county', models.CharField(max_length=20)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
            options={
                'ordering': ['name', 'county'],
            },
        ),
        migrations.CreateModel(
            name='TenantResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('geocoded_address', models.TextField(blank=True)),
                ('geocoded_latitude', models.FloatField(default=0.0)),
                ('geocoded_longitude', models.FloatField(default=0.0)),
                ('geocoded_point', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('catchment_area', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
                ('boroughs', models.ManyToManyField(blank=True, to='findhelp.Borough')),
                ('community_districts', models.ManyToManyField(blank=True, to='findhelp.CommunityDistrict')),
                ('neighborhoods', models.ManyToManyField(blank=True, to='findhelp.Neighborhood')),
            ],
        ),
        migrations.CreateModel(
            name='Zipcode',
            fields=[
                ('zipcode', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
            options={
                'ordering': ['zipcode'],
            },
        ),
        migrations.AddField(
            model_name='tenantresource',
            name='zipcodes',
            field=models.ManyToManyField(blank=True, to='findhelp.Zipcode'),
        ),
        migrations.AlterUniqueTogether(
            name='neighborhood',
            unique_together={('name', 'county')},
        ),
    ]
