# Generated by Django 2.1.5 on 2019-01-29 18:36

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('findhelp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantresource',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tenantresource',
            name='org_type',
            field=models.CharField(blank=True, choices=[('COMMUNITY', 'Community'), ('LEGAL', 'Legal'), ('GOVERNMENT', 'Government')], help_text='The organization type.', max_length=40),
        ),
        migrations.AddField(
            model_name='tenantresource',
            name='phone_number',
            field=models.CharField(blank=True, help_text='A U.S. phone number without parentheses or hyphens, e.g. "5551234567".', max_length=10, validators=[users.models.validate_phone_number], verbose_name='Phone number'),
        ),
        migrations.AddField(
            model_name='tenantresource',
            name='website',
            field=models.URLField(blank=True),
        ),
    ]
