# Generated by Django 2.1.5 on 2019-01-30 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findhelp', '0002_auto_20190129_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantresource',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
