# Generated by Django 2.2.18 on 2021-03-09 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('findhelp', '0005_county'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='county',
            options={'ordering': ['state', 'name'], 'verbose_name_plural': 'counties'},
        ),
    ]
