# Generated by Django 2.1 on 2018-09-06 15:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(choices=[('HOME', 'Entire home and hallways'), ('BEDROOMS', 'Bedrooms')], max_length=30)),
                ('value', models.CharField(choices=[('HOME__MICE', 'Mice'), ('HOME__RATS', 'Rats'), ('BEDROOMS__PAINT', 'Peeling paint'), ('BEDROOMS__WALLS', 'Cracked walls')], max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
