# Generated by Django 2.1 on 2018-09-07 14:16

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('issues', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='issue',
            unique_together={('user', 'value')},
        ),
    ]
