# Generated by Django 2.1 on 2018-09-07 14:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('issues', '0002_auto_20180907_1016'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomIssue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(choices=[('HOME', 'Entire home and hallways'), ('BEDROOMS', 'Bedrooms')], help_text='The area this custom issue belongs to.', max_length=30)),
                ('description', models.TextField(help_text='The description of this custom issue.')),
                ('user', models.ForeignKey(help_text='The user reporting the custom issue.', on_delete=django.db.models.deletion.CASCADE, related_name='custom_issues', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='customissue',
            unique_together={('user', 'area')},
        ),
    ]
