# Generated by Django 2.1 on 2018-09-25 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0003_auto_20180907_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customissue',
            name='area',
            field=models.CharField(choices=[('HOME', 'Entire home and hallways'), ('BEDROOMS', 'Bedrooms'), ('KITCHEN', 'Kitchen'), ('LIVING_ROOM', 'Living room'), ('BATHROOMS', 'Bathrooms'), ('PUBLIC_AREAS', 'Public areas'), ('LANDLORD', 'Landlord harassment')], help_text='The area this custom issue belongs to.', max_length=60),
        ),
        migrations.AlterField(
            model_name='issue',
            name='area',
            field=models.CharField(choices=[('HOME', 'Entire home and hallways'), ('BEDROOMS', 'Bedrooms'), ('KITCHEN', 'Kitchen'), ('LIVING_ROOM', 'Living room'), ('BATHROOMS', 'Bathrooms'), ('PUBLIC_AREAS', 'Public areas'), ('LANDLORD', 'Landlord harassment')], help_text='The area this issue belongs to.', max_length=60),
        ),
        migrations.AlterField(
            model_name='issue',
            name='value',
            field=models.CharField(choices=[('HOME__MICE', 'Mice'), ('HOME__RATS', 'Rats'), ('BEDROOMS__PAINT', 'Peeling paint'), ('BEDROOMS__WALLS', 'Cracked walls'), ('KITCHEN__MOLD', 'Mold on walls'), ('KITCHEN__WATER', 'Water damage'), ('LIVING_ROOM__PAINT', 'Peeling paint'), ('LIVING_ROOM__WALLS', 'Cracked walls'), ('BATHROOMS__PAINT', 'Peeling paint'), ('BATHROOMS__WALLS', 'Cracked walls'), ('PUBLIC_AREAS__PAINTING_OVERDUE', 'Painting overdue (3 years)'), ('PUBLIC_AREAS__PAINT', 'Peeling/flaking paint'), ('LANDLORD__RENT', 'Not receiving rent receipts'), ('LANDLORD__NO_LEASE', 'No lease')], help_text='The issue the user has reported.', max_length=60),
        ),
    ]
