# Generated by Django 2.1.2 on 2018-10-15 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0006_auto_20181004_2020'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='issue',
            options={'ordering': ('value',)},
        ),
    ]
