# Generated by Django 2.2.8 on 2019-12-10 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0009_auto_20191126_1028'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='customissue',
            unique_together=set(),
        ),
    ]
