# Generated by Django 2.2.13 on 2020-10-21 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0013_auto_20201012_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customissue',
            name='area',
            field=models.CharField(choices=[('BEDROOMS', 'Bedrooms'), ('KITCHEN', 'Kitchen'), ('LIVING_ROOM', 'Living room'), ('BATHROOMS', 'Bathrooms'), ('HOME', 'Home-wide'), ('PUBLIC_AREAS', 'Building-wide'), ('LANDLORD', 'Landlord harassment (currently hidden in app)')], help_text='The area this custom issue belongs to.', max_length=60),
        ),
        migrations.AlterField(
            model_name='issue',
            name='area',
            field=models.CharField(choices=[('BEDROOMS', 'Bedrooms'), ('KITCHEN', 'Kitchen'), ('LIVING_ROOM', 'Living room'), ('BATHROOMS', 'Bathrooms'), ('HOME', 'Home-wide'), ('PUBLIC_AREAS', 'Building-wide'), ('LANDLORD', 'Landlord harassment (currently hidden in app)')], help_text='The area this issue belongs to.', max_length=60),
        ),
    ]
