# Remember to set JUSTFIX_CELERY_BROKER_URL in your .justfix-env
# when using this file!
version: '2'
services:
  celery:
    extends:
      file: docker-services.yml
      service: base_app
    volumes:
      - .:/tenants2:delegated
    links:
        - db
    command: python manage.py runcelery
