version: '2'
services:
  app:
    environment:
      - CELERY_BROKER_URL=amqp://rabbitmq
    links:
      - db
      - rabbitmq
  rabbitmq:
    image: rabbitmq:3.7.17-alpine
  celery:
    extends:
      file: docker-services.yml
      service: base_app
    environment:
      - CELERY_BROKER_URL=amqp://rabbitmq
    volumes:
      - .:/tenants2:delegated
    links:
        - db
        - rabbitmq
    command: python manage.py runcelery
