version: '2'
services:
  app:
    extends:
      file: docker-services.yml
      service: base_app
    volumes:
      - .:/tenants2:delegated
    command: yarn server:start 0.0.0.0:8000
    links:
      - db
    ports:
      # The web server.
      - "8000:8000"
      # The remote debugger.
      - "5678:5678"
  frontend:
    extends:
      file: docker-services.yml
      service: base_app
    volumes:
      - .:/tenants2:delegated
    command: yarn start
    environment:
      - LAMBDA_POST_BUILD_NOTIFY_URL=http://app:8000/
  db:
    image: mdillon/postgis:10-alpine
    volumes:
      - pgdata:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=justfix
      - POSTGRES_USER=justfix
volumes:
  node-modules:
  unused-node-modules:
  python-venv:
  pgdata:
  yarn-cache:
  pipenv-cache:
