version: '2'
services:
  app:
    extends:
      file: docker-services.yml
      service: base_app
    volumes:
      - .:/tenants2:delegated
    command: python manage.py runserver 0.0.0.0:8000
    links:
      - db
      - redis
    ports:
      - "8000:8000"
  frontend:
    extends:
      file: docker-services.yml
      service: base_app
    volumes:
      - .:/tenants2:delegated
    command: yarn start
  db:
    image: mdillon/postgis:10-alpine
    volumes:
      - pgdata:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=justfix
      - POSTGRES_USER=justfix
  redis:
    image: redis:5.0.5
  celery:
    extends:
      file: docker-services.yml
      service: base_app
    volumes:
      - .:/tenants2:delegated
    links:
        - db
        - redis
    command: celery -A project worker -l info
volumes:
  node-modules:
  unused-node-modules:
  python-venv:
  pgdata:
  yarn-cache:
  pipenv-cache:
