version: '2'
services:
  app:
    extends:
      file: docker-services.yml
      service: base_app
    volumes:
      - .:/tenants2:delegated
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      - DATABASE_URL=postgis://justfix@db/justfix
    links:
      - db
    ports:
      - "8000:8000"
  frontend:
    extends:
      file: docker-services.yml
      service: base_app
    volumes:
      - .:/tenants2:delegated
    command: yarn start
  db:
    image: mdillon/postgis:10-alpine
    volumes:
      - pgdata:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=justfix
      - POSTGRES_USER=justfix
volumes:
  node-modules:
  unused-node-modules:
  python-venv:
  pgdata:
