# Generated by Django 3.2.13 on 2025-08-20 02:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import project.util.lob_django_util
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0011_justfixuser_preferred_first_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LetterSenderHabitabilityLetter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('locale', models.CharField(choices=[('en', 'English'), ('es', 'Spanish')], default='en', help_text="The locale of the user who sent the mail item, at the time that they sent it. Note that this may be different from the user's current locale, e.g. if they changed it after sending the mail item.", max_length=5)),
                ('lob_letter_object', models.JSONField(blank=True, help_text='If the mail item was sent via Lob, this is the JSON response of the API call that was made to send the mail item, documented at https://lob.com/docs/python#letters.', null=True)),
                ('tracking_number', models.CharField(blank=True, help_text='The USPS tracking number for the mail item.', max_length=100)),
                ('html_content', models.TextField(help_text='The HTML content of the letter at the time it was sent, in English.')),
                ('localized_html_content', models.TextField(blank=True, help_text="The HTML content of the letter at the time it was sent, in the user's locale at the time they sent it. If the user's locale is English, this will be blank (since the English version is already stored in another field).")),
                ('letter_sent_at', models.DateTimeField(blank=True, help_text='When the letter was mailed.', null=True)),
                ('letter_emailed_at', models.DateTimeField(blank=True, help_text='When the letter was e-mailed.', null=True)),
                ('fully_processed_at', models.DateTimeField(blank=True, help_text='When the letter was fully processed, i.e. sent to all relevant parties.', null=True)),
                ('mail_choice', models.TextField(choices=[('WE_WILL_MAIL', 'Mail for me'), ('USER_WILL_MAIL', 'Mail myself')], default='WE_WILL_MAIL', help_text='How the letter will be mailed.', max_length=30)),
                ('email_to_landlord', models.BooleanField(blank=True, help_text='Whether to email a copy of the letter to the landlord. Requires a landlord email to be provided', null=True)),
                ('pdf_base64', models.TextField(blank=True, help_text='A base64 encoded string representing the English content of the letter.')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lettersender_letters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
            bases=(models.Model, project.util.lob_django_util.SendableViaLobMixin),
        ),
        migrations.CreateModel(
            name='LaletterbuilderUser',
            fields=[
            ],
            options={
                'verbose_name': 'User with LATAC letter',
                'verbose_name_plural': 'Users with LATAC letters',
                'permissions': [('view_saje_users', 'Can view/download user data on behalf of SAJE'), ('view_rttc_users', 'Can view/download user data on behalf of RTTC')],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.justfixuser',),
            managers=[
                ('objects', users.models.JustfixUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='LetterSenderIssue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(choices=[('HEALTH__MOLD__BEDROOM', 'Mold'), ('HEALTH__MOLD__LIVING_ROOM', 'Mold'), ('HEALTH__MOLD__DINING_ROOM', 'Mold'), ('HEALTH__MOLD__BATHROOM', 'Mold'), ('HEALTH__MOLD__KITCHEN', 'Mold'), ('HEALTH__MOLD__HALLWAY', 'Mold'), ('HEALTH__MOLD__COMMON_AREAS', 'Mold'), ('HEALTH__PEELING_PAINT__BEDROOM', 'Peeling paint'), ('HEALTH__PEELING_PAINT__LIVING_ROOM', 'Peeling paint'), ('HEALTH__PEELING_PAINT__DINING_ROOM', 'Peeling paint'), ('HEALTH__PEELING_PAINT__BATHROOM', 'Peeling paint'), ('HEALTH__PEELING_PAINT__KITCHEN', 'Peeling paint'), ('HEALTH__PEELING_PAINT__HALLWAY', 'Peeling paint'), ('HEALTH__PEELING_PAINT__COMMON_AREAS', 'Peeling paint'), ('HEALTH__RODENT_INFESTATION__BEDROOM', 'Rodent infestation (mice, rats, ... )'), ('HEALTH__RODENT_INFESTATION__LIVING_ROOM', 'Rodent infestation (mice, rats, ... )'), ('HEALTH__RODENT_INFESTATION__DINING_ROOM', 'Rodent infestation (mice, rats, ... )'), ('HEALTH__RODENT_INFESTATION__BATHROOM', 'Rodent infestation (mice, rats, ... )'), ('HEALTH__RODENT_INFESTATION__KITCHEN', 'Rodent infestation (mice, rats, ... )'), ('HEALTH__RODENT_INFESTATION__HALLWAY', 'Rodent infestation (mice, rats, ... )'), ('HEALTH__RODENT_INFESTATION__COMMON_AREAS', 'Rodent infestation (mice, rats, ... )'), ('HEALTH__BUG_INFESTATION__BEDROOM', 'Bug infestation (roaches, bedbugs, ... )'), ('HEALTH__BUG_INFESTATION__LIVING_ROOM', 'Bug infestation (roaches, bedbugs, ... )'), ('HEALTH__BUG_INFESTATION__DINING_ROOM', 'Bug infestation (roaches, bedbugs, ... )'), ('HEALTH__BUG_INFESTATION__BATHROOM', 'Bug infestation (roaches, bedbugs, ... )'), ('HEALTH__BUG_INFESTATION__KITCHEN', 'Bug infestation (roaches, bedbugs, ... )'), ('HEALTH__BUG_INFESTATION__HALLWAY', 'Bug infestation (roaches, bedbugs, ... )'), ('HEALTH__BUG_INFESTATION__COMMON_AREAS', 'Bug infestation (roaches, bedbugs, ... )'), ('HEALTH__SMOKE_CO2_DETECTOR__BEDROOM', 'Smoke or carbon monoxide detector'), ('HEALTH__SMOKE_CO2_DETECTOR__LIVING_ROOM', 'Smoke or carbon monoxide detector'), ('HEALTH__SMOKE_CO2_DETECTOR__DINING_ROOM', 'Smoke or carbon monoxide detector'), ('HEALTH__SMOKE_CO2_DETECTOR__BATHROOM', 'Smoke or carbon monoxide detector'), ('HEALTH__SMOKE_CO2_DETECTOR__KITCHEN', 'Smoke or carbon monoxide detector'), ('HEALTH__SMOKE_CO2_DETECTOR__HALLWAY', 'Smoke or carbon monoxide detector'), ('HEALTH__SMOKE_CO2_DETECTOR__COMMON_AREAS', 'Smoke or carbon monoxide detector'), ('HEALTH__TRASH_CANS__BROKEN', 'Trash cans'), ('HEALTH__TRASH_CANS__NOT_ENOUGH', 'Trash cans'), ('HEALTH__TRASH_CANS__OTHER', 'Trash cans'), ('UTILITIES__DEFECTIVE_ELECTRICITY__BEDROOM', 'Defective electricity'), ('UTILITIES__DEFECTIVE_ELECTRICITY__LIVING_ROOM', 'Defective electricity'), ('UTILITIES__DEFECTIVE_ELECTRICITY__DINING_ROOM', 'Defective electricity'), ('UTILITIES__DEFECTIVE_ELECTRICITY__BATHROOM', 'Defective electricity'), ('UTILITIES__DEFECTIVE_ELECTRICITY__KITCHEN', 'Defective electricity'), ('UTILITIES__DEFECTIVE_ELECTRICITY__HALLWAY', 'Defective electricity'), ('UTILITIES__DEFECTIVE_ELECTRICITY__COMMON_AREAS', 'Defective electricity'), ('UTILITIES__SHUT_OFF__WATER', 'Utilities shut off (water, gas, ... )'), ('UTILITIES__SHUT_OFF__GAS', 'Utilities shut off (water, gas, ... )'), ('UTILITIES__SHUT_OFF__ELECTRICITY', 'Utilities shut off (water, gas, ... )'), ('UTILITIES__SHUT_OFF__OTHER', 'Utilities shut off (water, gas, ... )'), ('UTILITIES__WATER_LEAK__BATHROOM', 'Water leak'), ('UTILITIES__WATER_LEAK__KITCHEN', 'Water leak'), ('UTILITIES__WATER_LEAK__LAUNDRY_ROOM', 'Water leak'), ('UTILITIES__WATER_LEAK__COMMON_AREAS', 'Water leak'), ('UTILITIES__DEFECTIVE_PLUMBING__BEDROOM', 'Defective plumbing'), ('UTILITIES__DEFECTIVE_PLUMBING__LIVING_ROOM', 'Defective plumbing'), ('UTILITIES__DEFECTIVE_PLUMBING__DINING_ROOM', 'Defective plumbing'), ('UTILITIES__DEFECTIVE_PLUMBING__BATHROOM', 'Defective plumbing'), ('UTILITIES__DEFECTIVE_PLUMBING__KITCHEN', 'Defective plumbing'), ('UTILITIES__DEFECTIVE_PLUMBING__HALLWAY', 'Defective plumbing'), ('UTILITIES__DEFECTIVE_PLUMBING__COMMON_AREAS', 'Defective plumbing'), ('UTILITIES__NO_HOT_WATER__BATHROOM', 'No hot water'), ('UTILITIES__NO_HOT_WATER__KITCHEN', 'No hot water'), ('UTILITIES__NO_HOT_WATER__LAUNDRY_ROOM', 'No hot water'), ('UTILITIES__NO_HOT_WATER__COMMON_AREAS', 'No hot water'), ('BUILDING_AND_SAFETY__HOLES__BEDROOM', 'Holes'), ('BUILDING_AND_SAFETY__HOLES__LIVING_ROOM', 'Holes'), ('BUILDING_AND_SAFETY__HOLES__DINING_ROOM', 'Holes'), ('BUILDING_AND_SAFETY__HOLES__BATHROOM', 'Holes'), ('BUILDING_AND_SAFETY__HOLES__KITCHEN', 'Holes'), ('BUILDING_AND_SAFETY__HOLES__HALLWAY', 'Holes'), ('BUILDING_AND_SAFETY__HOLES__COMMON_AREAS', 'Holes'), ('BUILDING_AND_SAFETY__BROKEN_WINDOWS__BEDROOM', 'Broken/defective windows'), ('BUILDING_AND_SAFETY__BROKEN_WINDOWS__LIVING_ROOM', 'Broken/defective windows'), ('BUILDING_AND_SAFETY__BROKEN_WINDOWS__DINING_ROOM', 'Broken/defective windows'), ('BUILDING_AND_SAFETY__BROKEN_WINDOWS__BATHROOM', 'Broken/defective windows'), ('BUILDING_AND_SAFETY__BROKEN_WINDOWS__KITCHEN', 'Broken/defective windows'), ('BUILDING_AND_SAFETY__BROKEN_WINDOWS__HALLWAY', 'Broken/defective windows'), ('BUILDING_AND_SAFETY__BROKEN_WINDOWS__COMMON_AREAS', 'Broken/defective windows'), ('BUILDING_AND_SAFETY__INSECURE_LOCKS__FRONT_DOOR', 'Broken/insecure locks'), ('BUILDING_AND_SAFETY__INSECURE_LOCKS__BACK_DOOR', 'Broken/insecure locks'), ('BUILDING_AND_SAFETY__INSECURE_LOCKS__BUILDING_MAIN_ENTRANCE', 'Broken/insecure locks'), ('BUILDING_AND_SAFETY__INSECURE_LOCKS__BUILDING_PARKING_ENTRANCE', 'Broken/insecure locks'), ('BUILDING_AND_SAFETY__FAULTY_DOORS__FRONT_DOOR', 'Faulty doors'), ('BUILDING_AND_SAFETY__FAULTY_DOORS__BACK_DOOR', 'Faulty doors'), ('BUILDING_AND_SAFETY__FAULTY_DOORS__BUILDING_MAIN_ENTRANCE', 'Faulty doors'), ('BUILDING_AND_SAFETY__FAULTY_DOORS__BUILDING_PARKING_ENTRANCE', 'Faulty doors'), ('BUILDING_AND_SAFETY__UNSAFE_STAIRS__BUILDING_MAIN_ENTRANCE', 'Unsafe/broken stairs and/or railing'), ('BUILDING_AND_SAFETY__UNSAFE_STAIRS__BUILDING_EXIT', 'Unsafe/broken stairs and/or railing'), ('BUILDING_AND_SAFETY__UNSAFE_STAIRS__FLOOR_LEVEL', 'Unsafe/broken stairs and/or railing'), ('BUILDING_AND_SAFETY__UNSAFE_STAIRS__OTHER', 'Unsafe/broken stairs and/or railing')], help_text='The issue the letter is reporting.', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('letter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lettersender_issues', to='lettersender.lettersenderhabitabilityletter')),
            ],
            options={
                'ordering': ('value',),
                'unique_together': {('letter', 'value')},
            },
        ),
    ]
