# Generated by Django 3.2.13 on 2025-08-20 17:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import project.util.lob_django_util
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_justfixuser_preferred_first_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lettersender', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LetterSenderLetter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('locale', models.CharField(choices=[('en', 'English'), ('es', 'Spanish')], default='en', help_text="The locale of the user who sent the mail item, at the time that they sent it. Note that this may be different from the user's current locale, e.g. if they changed it after sending the mail item.", max_length=5)),
                ('lob_letter_object', models.JSONField(blank=True, help_text='If the mail item was sent via Lob, this is the JSON response of the API call that was made to send the mail item, documented at https://lob.com/docs/python#letters.', null=True)),
                ('tracking_number', models.CharField(blank=True, help_text='The USPS tracking number for the mail item.', max_length=100)),
                ('html_content', models.TextField(help_text='The HTML content of the letter at the time it was sent, in English.')),
                ('localized_html_content', models.TextField(blank=True, help_text="The HTML content of the letter at the time it was sent, in the user's locale at the time they sent it. If the user's locale is English, this will be blank (since the English version is already stored in another field).")),
                ('letter_sent_at', models.DateTimeField(blank=True, help_text='When the letter was mailed.', null=True)),
                ('letter_emailed_at', models.DateTimeField(blank=True, help_text='When the letter was e-mailed.', null=True)),
                ('fully_processed_at', models.DateTimeField(blank=True, help_text='When the letter was fully processed, i.e. sent to all relevant parties.', null=True)),
                ('mail_choice', models.TextField(choices=[('WE_WILL_MAIL', 'Mail for me'), ('USER_WILL_MAIL', 'Mail myself')], default='WE_WILL_MAIL', help_text='How the letter will be mailed.', max_length=30)),
                ('email_to_landlord', models.BooleanField(blank=True, help_text='Whether to email a copy of the letter to the landlord. Requires a landlord email to be provided', null=True)),
                ('pdf_base64', models.TextField(blank=True, help_text='A base64 encoded string representing the English content of the letter.')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lettersender_letters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
            bases=(models.Model, project.util.lob_django_util.SendableViaLobMixin),
        ),
        migrations.RemoveField(
            model_name='lettersenderhabitabilityletter',
            name='user',
        ),
        migrations.DeleteModel(
            name='LaletterbuilderUser',
        ),
        migrations.CreateModel(
            name='LetterSenderUser',
            fields=[
            ],
            options={
                'verbose_name': 'User with Letter Sender letter',
                'verbose_name_plural': 'Users with Letter Sender letters',
                'permissions': [('view_saje_users', 'Can view/download user data on behalf of SAJE'), ('view_rttc_users', 'Can view/download user data on behalf of RTTC')],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.justfixuser',),
            managers=[
                ('objects', users.models.JustfixUserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='lettersenderissue',
            name='value',
            field=models.CharField(choices=[('INFORM_RIGHTS', 'I want to inform my landlord about my Good Cause Eviction rights'), ('OVERCHARGE', 'I am being overcharged for rent or will soon be overcharged for rent'), ('EVICTION', 'I am being evicted without reason'), ('NO_RENEWAL', 'I am not being offered a lease renewal')], help_text='The issue the letter is reporting.', max_length=100),
        ),
        migrations.AlterField(
            model_name='lettersenderissue',
            name='letter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lettersender_gce_issues', to='lettersender.lettersenderletter'),
        ),
        migrations.DeleteModel(
            name='LetterSenderHabitabilityLetter',
        ),
    ]
