# Generated by Django 3.2.13 on 2025-08-21 18:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lettersender', '0002_auto_20250820_1750'),
    ]

    operations = [
        migrations.CreateModel(
            name='LetterSenderOverchargeDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overcharge_applies', models.BooleanField(help_text='Whether the overcharge situation applies to the user.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lettersender_overcharge_details', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Letter Sender Overcharge Details',
                'verbose_name_plural': 'Letter Sender Overcharge Details',
            },
        ),
    ]
