# Generated by Django 2.1 on 2018-08-17 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LegacyUserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('TENANT', 'Tenant'), ('ADVOCATE', 'Advocate')], max_length=30)),
                ('phone_number', models.CharField(max_length=10, unique=True)),
            ],
        ),
    ]
