# Generated by Django 2.1 on 2018-08-16 12:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LegacyUserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('TENANT', 'Tenant'), ('ADVOCATE', 'Advocate')], max_length=30)),
                ('mongo_id', models.CharField(max_length=24, unique=True)),
                ('phone_number', models.CharField(max_length=10, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='legacy_info', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
