# Generated by Django 2.1.2 on 2018-10-03 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legacy_tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='legacyuserinfo',
            name='prefers_legacy_app',
            field=models.BooleanField(default=True, help_text='Whether we should redirect this user to the legacy tenant app after they log in.'),
        ),
    ]
