# Generated by Django 2.1 on 2018-08-17 14:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('legacy_tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='legacyuserinfo',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='legacy_info', to=settings.AUTH_USER_MODEL),
        ),
    ]
