# Generated by Django 2.2.10 on 2020-04-25 16:57

from django.db import migrations, models
import project.util.phone_number


class Migration(migrations.Migration):

    dependencies = [
        ('legacy_tenants', '0002_legacyuserinfo_prefers_legacy_app'),
    ]

    operations = [
        migrations.AddField(
            model_name='legacyuserinfo',
            name='original_phone_number',
            field=models.CharField(blank=True, help_text='A U.S. phone number without parentheses or hyphens, e.g. "5551234567".', max_length=10, validators=[project.util.phone_number.validate_phone_number]),
        ),
    ]
