# Generated by Django 2.2.4 on 2019-11-26 12:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import project.util.phone_number


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RentalHistoryRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=150)),
                ('apartment_number', models.CharField(max_length=15)),
                ('phone_number', models.CharField(help_text='A U.S. phone number without parentheses or hyphens, e.g. "5551234567".', max_length=10, validators=[project.util.phone_number.validate_phone_number])),
                ('address', models.CharField(max_length=200)),
                ('address_verified', models.BooleanField()),
                ('borough', models.CharField(choices=[('BROOKLYN', 'Brooklyn'), ('QUEENS', 'Queens'), ('BRONX', 'Bronx'), ('MANHATTAN', 'Manhattan'), ('STATEN_ISLAND', 'Staten Island')], max_length=20)),
                ('user', models.ForeignKey(blank=True, help_text="User who was logged in when the rental history request was made. This may or may not be different from the actual name/address of the request, e.g. if the user is making a request on someone else's behalf.", null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
