# Generated by Django 2.2.9 on 2020-02-18 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalhistoryrequest',
            name='zipcode',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
