# Generated by Django 2.2.13 on 2020-08-26 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0002_rentalhistoryrequest_zipcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalhistoryrequest',
            name='address',
            field=models.CharField(max_length=64),
        ),
    ]
