# Generated by Django 3.2.13 on 2024-01-17 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0003_auto_20200826_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalhistoryrequest',
            name='referral',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
