# Generated by Django 3.2.13 on 2024-01-18 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partnerships', '0001_initial'),
        ('rh', '0004_rentalhistoryrequest_referral'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalhistoryrequest',
            name='referral',
            field=models.ForeignKey(blank=True, db_column='referral', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='partnerships.partnerorg', to_field='name'),
        ),
    ]
