# Generated by Django 3.2.13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0007_rentalhistoryrequest_referral'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalhistoryrequest',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='rentalhistoryrequest',
            name='request_source',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='rentalhistoryrequest',
            name='submission_success',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rentalhistoryrequest',
            name='dhcr_ref_number',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
