# Generated by Django 3.2.13 on 2026-05-26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0007_rentalhistoryrequest_referral"),
    ]

    operations = [
        migrations.AddField(
            model_name="rentalhistoryrequest",
            name="dhcr_reference_number",
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
