# Generated by Django 2.2.10 on 2020-04-21 19:28

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RentPeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField(help_text='The date rent payment is due.', unique=True)),
            ],
            options={
                'ordering': ['-payment_date'],
            },
        ),
        migrations.CreateModel(
            name='Letter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('html_content', models.TextField(help_text='The HTML content of the letter at the time it was sent.')),
                ('lob_letter_object', django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='If the letter was sent via Lob, this is the JSON response of the API call that was made to send the letter, documented at https://lob.com/docs/python#letters.', null=True)),
                ('tracking_number', models.CharField(blank=True, help_text='The tracking number for the letter.', max_length=100)),
                ('letter_sent_at', models.DateTimeField(blank=True, help_text='When the letter was mailed.', null=True)),
                ('letter_emailed_at', models.DateTimeField(blank=True, help_text='When the letter was e-mailed.', null=True)),
                ('rent_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='norent.RentPeriod')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-rent_period__payment_date'],
                'unique_together': {('user', 'rent_period')},
            },
        ),
    ]
