# Generated by Django 2.2.10 on 2020-05-21 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('norent', '0002_auto_20200502_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='letter',
            name='locale',
            field=models.CharField(choices=[('en', 'English'), ('es', 'Spanish')], default='en', help_text="The locale of the user who sent the letter, at the time that they sent it. Note that this may be different from the user's current locale, e.g. if they changed it after sending the letter.", max_length=5),
        ),
        migrations.AddField(
            model_name='letter',
            name='localized_html_content',
            field=models.TextField(blank=True, help_text="The HTML content of the letter at the time it was sent, in the user's locale at the time they sent it. If the user's locale is English, this will be blank (since the English version is already stored in another field)."),
        ),
        migrations.AlterField(
            model_name='letter',
            name='html_content',
            field=models.TextField(help_text='The HTML content of the letter at the time it was sent, in English.'),
        ),
    ]
