# Generated by Django 2.2.13 on 2020-10-05 18:07

from django.db import migrations


def forward(apps, schema_editor):
    # https://ponytech.net/blog/convert-foreign-key-many-to-many-using-django-migrations
    Letter = apps.get_model("norent", "Letter")
    for letter in Letter.objects.all():
        letter.rent_periods.add(letter.rent_period)


class Migration(migrations.Migration):

    dependencies = [
        ('norent', '0004_add_rent_periods'),
    ]

    operations = [
        migrations.RunPython(forward),
    ]
