# Generated by Django 2.2.13 on 2020-10-05 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('norent', '0005_rent_periods_m2m'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='letter',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterUniqueTogether(
            name='letter',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='letter',
            name='rent_period',
        ),
    ]
