# Generated by Django 2.2.13 on 2020-10-07 11:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('norent', '0006_remove_rent_period'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpcomingLetterRentPeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rent_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='norent.RentPeriod')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upcoming_norent_letter_rent_periods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'rent_period')},
            },
        ),
    ]
