# Generated by Django 2.2.13 on 2020-11-09 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('norent', '0007_upcomingletterrentperiod'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='norentuser',
            options={'permissions': [('view_saje_users', 'Can view/download user data on behalf of SAJE'), ('view_rttc_users', 'Can view/download user data on behalf of RTTC')], 'verbose_name': 'User with NoRent letter', 'verbose_name_plural': 'Users with NoRent letters'},
        ),
    ]
