# Generated by Django 2.2.18 on 2021-02-25 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('norent', '0008_auto_20201109_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='letter',
            name='fully_processed_at',
            field=models.DateTimeField(blank=True, help_text='When the letter was fully processed, i.e. sent to all relevant parties.', null=True),
        ),
    ]
