# Generated by Django 3.2.12 on 2022-06-28 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('norent', '0012_auto_20211206_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='letter',
            name='pdf_base64',
            field=models.TextField(blank=True, help_text='A base64 encoded string representing the English content of the letter.'),
        ),
    ]
