SELECT
	CASE
		WHEN N.DEVELOPMENT IS NOT NULL THEN 'NYCHA'
		WHEN R.UC2024 > 0 THEN 'RENT_STABILIZED'
		WHEN P.UNITSRES > 0 THEN 'MARKET_RATE'
		ELSE NULL
	END AS HOUSINGTYPE
FROM PLUTO_LATEST P
LEFT JOIN RENTSTAB_V2 R ON P.BBL = UCBBL
LEFT JOIN NYCHA_BBLS_18 N USING(BBL)
WHERE BBL = %(bbl)s
LIMIT 1
