# Generated by Django 3.2.5 on 2022-01-11 21:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    replaces = [('laletterbuilder', '0001_initial'), ('laletterbuilder', '0002_delete_laletterdetails')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
    ]
