# Generated by Django 3.2.5 on 2021-12-13 21:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LaLetterDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter_type', models.CharField(blank=True, choices=[('HABITABILITY', 'Habitability (CA)'), ('CA_HARASSMENT', 'Harassment (CA)'), ('LA_HARASSMENT', 'Harassment (LA City/TAHO)'), ('PRIVACY', 'Right to Privacy (CA)')], help_text='The type of letter the tenant is creating in this session.', max_length=20)),
                ('user', models.ForeignKey(help_text='The user these letter details relate to', on_delete=django.db.models.deletion.CASCADE, related_name='la_letter_details', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
