# Generated by Django 3.2.12 on 2022-03-23 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('laletterbuilder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaIssue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value', models.CharField(choices=[('HEALTH__MOLD__BEDROOM', 'Mold'), ('HEALTH__MOLD__KITCHEN', 'Mold'), ('HEALTH__PEELING_PAINT__BEDROOM', 'Peeling paint'), ('HEALTH__PEELING_PAINT__KITCHEN', 'Peeling paint'), ('HEALTH__RODENT_INFESTATION__BEDROOM', 'Rodent infestation'), ('HEALTH__RODENT_INFESTATION__KITCHEN', 'Rodent infestation'), ('UTILITIES__DEFECTIVE_ELECTRICITY__BEDROOM', 'Defective electricity'), ('UTILITIES__DEFECTIVE_ELECTRICITY__KITCHEN', 'Defective electricity'), ('UTILITIES__WATER_LEAK__BEDROOM', 'Water leak'), ('UTILITIES__WATER_LEAK__KITCHEN', 'Water leak'), ('BUILDING_AND_SAFETY__HOLES__BEDROOM', 'Holes'), ('BUILDING_AND_SAFETY__HOLES__KITCHEN', 'Holes'), ('BUILDING_AND_SAFETY__BROKEN_LOCKS__BEDROOM', 'Broken locks'), ('BUILDING_AND_SAFETY__BROKEN_LOCKS__KITCHEN', 'Broken locks')], help_text='The issue the letter is reporting.', max_length=60)),
                ('letter', models.ForeignKey(help_text='The letter reporting the issue.', on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='laletterbuilder.habitabilityletter')),
            ],
            options={
                'ordering': ('value',),
                'unique_together': {('letter', 'value')},
            },
        ),
    ]
