# Generated by Django 3.2.5 on 2022-01-11 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laletterbuilder', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LaLetterDetails',
        ),
    ]
