# Generated by Django 3.2.12 on 2022-04-28 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('laletterbuilder', '0003_auto_20220420_1959'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaAccessDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text="The date on which the user's dwelling will be accessible.")),
                ('start_time', models.TimeField(help_text="The start time at which the user's dwelling will be accessible.")),
                ('end_time', models.TimeField(help_text="The end time at which the user's dwelling will be accessible.")),
                ('letter', models.ForeignKey(help_text='The letter for which access dates are set.', on_delete=django.db.models.deletion.CASCADE, related_name='access_dates', to='laletterbuilder.habitabilityletter')),
            ],
            options={
                'unique_together': {('letter', 'date', 'start_time', 'end_time')},
            },
        ),
    ]
