# Generated by Django 3.2.12 on 2022-06-15 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laletterbuilder', '0004_habitabilityletter_mail_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitabilityletter',
            name='email_to_landlord',
            field=models.BooleanField(default=False, help_text='Whether to email a copy of the letter to the landlord. Requires a landlord email to be provided'),
        ),
        migrations.AlterField(
            model_name='habitabilityletter',
            name='mail_choice',
            field=models.TextField(choices=[('WE_WILL_MAIL', 'Mail for me'), ('USER_WILL_MAIL', 'Mail myself')], default='WE_WILL_MAIL', help_text='How the letter will be mailed.', max_length=30),
        ),
    ]
