from django.core.management.base import BaseCommand
from datetime import datetime
from django.utils.timezone import make_aware
from pytz import timezone

from loc.models import LetterRequest, LOC_MAILING_CHOICES
from hpaction.models import HPActionDocuments


class Command(BaseCommand):
    help = 'Display statistics for the 2019 annual report.'

    def handle(self, *args, **options):
        eastern = timezone('US/Eastern')
        start = make_aware(datetime(2019, 1, 1), eastern)
        end = make_aware(datetime(2019, 12, 31), eastern)

        loc_requests = LetterRequest.objects.filter(
            letter_sent_at__gte=start,
            letter_sent_at__lte=end,
        )
        print(f"Total letters we sent in {start.year}: {loc_requests.count()}")

        user_will_mail_loc_requests = LetterRequest.objects.filter(
            created_at__gte=start,
            created_at__lte=end,
            mail_choice=LOC_MAILING_CHOICES.USER_WILL_MAIL,
        )
        print(f"Total letters sent by other users in {start.year}: "
              f"{user_will_mail_loc_requests.count()}")

        hp_packets_created = HPActionDocuments.objects.filter(
            created_at__gte=start,
            created_at__lte=make_aware(datetime.now(), eastern),
        ).distinct('user')
        print(
            f"Total HP Action packets generated by unique users from {start.year} to now: "
            f"{hp_packets_created.count()}"
        )
