import * as path from 'path';
import { combineGlobs } from './util';

/**
 * The following directory paths assume we've been compiled to the
 * root project dir, and that we're running from it as well.
 */

/** The extension for all our GraphQL queries/mutations/fragments. */
export const DOT_GRAPHQL = '.graphql';

/**
 * The path to the directory where we'll get our GraphQL queries, and
 * where we'll put our generated TypeScript source code.
 */
export const QUERIES_PATH_PARTS = ['frontend', 'lib', 'queries'];
export const QUERIES_PATH = path.join(...QUERIES_PATH_PARTS);

/**
 * Path to the configuration file for the GraphQL files we automatically generate.
 */
export const AUTOGEN_CONFIG_PATH = path.join(QUERIES_PATH, 'autogen-config.toml');

/** The preamble at the top of GraphQL files we automatically generate. */
export const AUTOGEN_PREAMBLE =
  `# This file was auto-generated by querybuilder, please do not edit it.\n`;

/**
 * The output directory where automatically generated GraphQL files will
 * be placed.
 */
export const AUTOGEN_QUERIES_PATH = path.join(QUERIES_PATH, 'autogen');

/**
 * The directories containing all GraphQL queries that are
 * written "by hand" (i.e., not autogenerated). */
const WATCHABLE_QUERY_PATHS = [
  QUERIES_PATH,
];

/** The directories containing all our GraphQL queries. */
const ALL_QUERY_PATHS = [
  ...WATCHABLE_QUERY_PATHS,
  AUTOGEN_QUERIES_PATH
];

/**
 * Helper that converts a list of dirs to a glob for all GraphQL
 * files in those dirs.
 */
const graphQlGlobify = (paths: string[]) =>
  combineGlobs(paths.map(path => `${path}/*${DOT_GRAPHQL}`));

/** The glob that locates all our "handwritten" GraphQL queries. */
export const WATCHABLE_QUERIES_GLOB = graphQlGlobify(WATCHABLE_QUERY_PATHS);

/** The glob that locates all our GraphQL queries. */
export const QUERIES_GLOB = graphQlGlobify(ALL_QUERY_PATHS);

/** The path into which Apollo codegen:generate will put its generated files. */
export const APOLLO_GEN_PATH = path.join(QUERIES_PATH, '__generated__');

/** The location of the GraphQL schema for the server. */
export const GRAPHQL_SCHEMA_PATH = path.join('schema.json');

/**
 * Files generated by Apollo codegen:generate that we want to copy over to
 * our destination directory, without modifying.
 */
export const COPY_FROM_APOLLO_GEN_TO_QUERIES = [
  'globalTypes.ts',
];
