import * as path from 'path';

/**
 * The following directory paths assume we've been compiled to the
 * root project dir, and that we're running from it as well.
 */

/**
 * The path to the directory where we'll get our GraphQL queries, and
 * where we'll put our generated TypeScript source code.
 */
export const QUERIES_PATH_PARTS = ['frontend', 'lib', 'queries'];
export const QUERIES_PATH = path.join(...QUERIES_PATH_PARTS);

/**
 * Path to the configuration file for the GraphQL files we automatically generate.
 */
export const AUTOGEN_CONFIG_PATH = path.join(QUERIES_PATH, 'autogen-config.toml');

/** The preamble at the top of GraphQL files we automatically generate. */
export const AUTOGEN_PREAMBLE =
  `# This file was auto-generated by querybuilder, please do not edit it.\n`;

/** The glob that locates all our GraphQL queries. */
export const QUERIES_GLOB = `${QUERIES_PATH}/*.graphql`;

/** The path into which Apollo codegen:generate will put its generated files. */
export const APOLLO_GEN_PATH = path.join(QUERIES_PATH, '__generated__');

/** The location of the GraphQL schema for the server. */
export const GRAPHQL_SCHEMA_PATH = path.join('schema.json');

/** The extension for all our GraphQL queries/mutations/fragments. */
export const DOT_GRAPHQL = '.graphql';

/**
 * Files generated by Apollo codegen:generate that we want to copy over to
 * our destination directory, without modifying.
 */
export const COPY_FROM_APOLLO_GEN_TO_QUERIES = [
  'globalTypes.ts',
];
