version: 2
jobs:
  build:
    working_directory: ~/tenants2
    docker:
      - image: justfixnyc/tenants2_base:0.1
        environment:
          PIPENV_VENV_IN_PROJECT: true
          DEBUG: yup
          CC_TEST_REPORTER_ID: 0b47f78787493d017e97f3f141ab138e9188d1ebbe149bb0f28a8ff3314dfdd7
    steps:
      - checkout
      - restore_cache:
          key: tenants2-take2-{{ .Branch }}-{{ checksum "Pipfile.lock" }}-{{ checksum "package-lock.json" }}-{{ checksum "requirements.production.txt" }}
      - run:
          command: |
             pipenv sync --dev
             npm install --no-save
             pipenv run pip install -r requirements.production.txt
      - save_cache:
          key: tenants2-take2-{{ .Branch }}-{{ checksum "Pipfile.lock" }}-{{ checksum "package-lock.json" }}-{{ checksum "requirements.production.txt" }}
          paths:
            - ".venv"
            - "node_modules"
      - run:
          name: CodeClimate before-build
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
            ./cc-test-reporter before-build
      - run:
          command: |
            node --version
            npm run build
            npm test -- --runInBand
            npm run lint
            pipenv run "pytest" --cov-report xml:./coverage/python/coverage.xml
      - run:
          name: CodeClimate combine and upload coverage
          command: |
            # Format the various coverage reports
            ./cc-test-reporter format-coverage -t lcov -o coverage/codeclimate.jest.json coverage/jest/lcov.info
            ./cc-test-reporter format-coverage -t coverage.py -o coverage/codeclimate.python.json coverage/python/coverage.xml
            # Combine the test coverage reports
            ./cc-test-reporter sum-coverage coverage/codeclimate.*.json
            # Attempt to submit the coverage report, but don't fail the build if this fails (`|| true`)
            ./cc-test-reporter upload-coverage --debug || true
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
          destination: tr1
