version: 2
jobs:
  build:
    working_directory: ~/tenants2
    docker:
      - image: circleci/python:3.7
        environment:
          PIPENV_VENV_IN_PROJECT: true
          DEBUG: yup
    steps:
      - checkout
      - restore_cache:
          key: tenants2-take2-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
      - run:
          command: |
             pipenv sync --dev
      - save_cache:
          key: tenants2-take2-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
          paths:
            - ".venv"
      - run:
          command: |
            pipenv run "pytest"
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
          destination: tr1
