# Generated by Django 2.1.4 on 2019-01-03 15:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import pyotp


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TwofactorInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret', models.CharField(default=pyotp.random_base32, help_text='The Time-based One-time Password (TOTP) secret for this user.', max_length=16)),
                ('has_user_seen_secret_yet', models.BooleanField(default=False, help_text="Whether or not we've shown the TOTP secret to the user yet. If false, we will show it to them when they next need to be verified; otherwise we will assume they have stored it.")),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='twofactor_info', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
