# Generated by Django 2.1.7 on 2019-03-19 23:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactGroup',
            fields=[
                ('uuid', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Metadata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_sync', models.DateTimeField(help_text='The date and time RapidPro was last synced with, if ever.', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserContactGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earliest_known_date', models.DateTimeField(help_text='The earliest known date/time the user was seen in this contact group.')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rapidpro.ContactGroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='contactgroup',
            name='users',
            field=models.ManyToManyField(through='rapidpro.UserContactGroup', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='usercontactgroup',
            unique_together={('user', 'group')},
        ),
    ]
