import { createDjangoChoicesTypescript, createDjangoChoicesTypescriptFiles } from "../commondatabuilder";

import ourConfig from "../../../common-data/config";

const EXPECTED_TS = `// This file was auto-generated by commondatabuilder.
// Please don't edit it.

export enum BoroughChoice {
  BROOKLYN = "BROOKLYN",
}

export type BoroughChoiceLabels = {
  [k in BoroughChoice]: string;
};

export function getBoroughChoiceLabels(): BoroughChoiceLabels {
  return {
    BROOKLYN: "Brooklyn",
  };
}
`;

describe('commondatabuilder', () => {
  it('creates django choice typescript', () => {
    const ts = createDjangoChoicesTypescript([['BROOKLYN', 'Brooklyn']], 'BoroughChoice');
    expect(ts).toEqual(EXPECTED_TS);
  });

  it('only exports labels if configured to', () => {
    expect(createDjangoChoicesTypescript([], 'Foo')).toMatch(/getFooLabels/);
    expect(createDjangoChoicesTypescript([], 'Foo', {
      exportLabels: false
    })).not.toMatch(/getFooLabels/);
  });

  it('works with our common data configuration', () => {
    createDjangoChoicesTypescriptFiles(ourConfig, true);
  });
});
