# Generated by Django 2.2.13 on 2021-01-20 20:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HardshipDeclarationDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_number', models.CharField(blank=True, help_text="The user's existing eviction case index number, if any.", max_length=80)),
                ('has_financial_hardship', models.BooleanField(default=False, help_text='Whether the user has COVID-19 related financial hardship.')),
                ('has_health_risk', models.BooleanField(default=False, help_text='Whether the user has COVID-19 related heath risk.')),
                ('user', models.OneToOneField(help_text='The user whom these hardship declaration details are for.', on_delete=django.db.models.deletion.CASCADE, related_name='hardship_declaration_details', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
