# Generated by Django 2.2.13 on 2021-01-27 22:53

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_justfixuser_locale'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('evictionfree', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvictionFreeUser',
            fields=[
            ],
            options={
                'verbose_name': 'User with EvictionFreeNY declaration',
                'verbose_name_plural': 'Users with EvictionFreeNY declarations',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.justfixuser',),
            managers=[
                ('objects', users.models.JustfixUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='SubmittedHardshipDeclaration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('locale', models.CharField(choices=[('en', 'English'), ('es', 'Spanish')], default='en', help_text="The locale of the user who sent the letter, at the time that they sent it. Note that this may be different from the user's current locale, e.g. if they changed it after sending the letter.", max_length=5)),
                ('cover_letter_variables', django.contrib.postgres.fields.jsonb.JSONField(help_text='The variables used to fill out the cover letter page.')),
                ('cover_letter_html', models.TextField(help_text="The HTML content of the declaration's cover letter.")),
                ('declaration_variables', django.contrib.postgres.fields.jsonb.JSONField(help_text='The variables used to fill out the declaration form PDF.')),
                ('lob_letter_object', django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='If the declaration was sent via Lob, this is the JSON response of the API call that was made to send the letter, documented at https://lob.com/docs/python#letters.', null=True)),
                ('tracking_number', models.CharField(blank=True, help_text='The USPS tracking number for the declaration.', max_length=100)),
                ('mailed_at', models.DateTimeField(blank=True, help_text="When the declaration was mailed to the user's landlord.", null=True)),
                ('emailed_at', models.DateTimeField(blank=True, help_text="When the declaration was e-mailed to the user's landlord.", null=True)),
                ('emailed_to_housing_court_at', models.DateTimeField(blank=True, help_text="When the declaration was e-mailed to the user's housing court.", null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_hardship_declaration', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
