# Generated by Django 2.2.13 on 2021-01-28 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evictionfree', '0002_evictionfreeuser_submittedhardshipdeclaration'),
    ]

    operations = [
        migrations.AddField(
            model_name='submittedhardshipdeclaration',
            name='emailed_to_user_at',
            field=models.DateTimeField(blank=True, help_text='When the declaration was e-mailed to the user.', null=True),
        ),
    ]
