# Generated by Django 2.2.13 on 2021-01-27 22:33

from django.db import migrations
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_justfixuser_locale'),
        ('evictionfree', '0002_submittedhardshipdeclaration'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvictionFreeUser',
            fields=[
            ],
            options={
                'verbose_name': 'User with EvictionFreeNY declaration',
                'verbose_name_plural': 'Users with EvictionFreeNY declarations',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.justfixuser',),
            managers=[
                ('objects', users.models.JustfixUserManager()),
            ],
        ),
    ]
