# Generated by Django 2.2.18 on 2021-03-15 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evictionfree', '0005_auto_20210201_2352'),
    ]

    operations = [
        migrations.AddField(
            model_name='hardshipdeclarationdetails',
            name='court_name',
            field=models.CharField(blank=True, help_text="The court the user's existing eviction case is at, if any.", max_length=80),
        ),
    ]
