# Generated by Django 3.2.4 on 2021-07-21 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('url', models.URLField(help_text='The destination of the link.')),
                ('title', models.CharField(help_text='The title of the link.', max_length=200)),
                ('slug', models.SlugField(help_text='The slug of the link. This will be used in the short link, so try to keep it short yet (hopefully) memorable.', max_length=200, unique=True)),
                ('description', models.TextField(blank=True, help_text='A description of the link. Optional.')),
            ],
        ),
    ]
