# Generated by Django 3.2.4 on 2021-08-25 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortlinks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='slug',
            field=models.SlugField(help_text="The slug of the link. This will be used in the short link, so try to keep it short yet (hopefully) memorable. NOTE: the slug will be saved as fully lowercase (i.e. 'hOMe' will be saved as 'home').", max_length=200, unique=True),
        ),
    ]
