# Generated by Django 3.2.13 on 2025-08-27 17:44

from django.db import migrations, models
import django.db.models.deletion
import project.util.lob_django_util
import project.util.mailing_address
import project.util.phone_number


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GCELetter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('locale', models.CharField(choices=[('en', 'English'), ('es', 'Spanish')], default='en', help_text="The locale of the user who sent the mail item, at the time that they sent it. Note that this may be different from the user's current locale, e.g. if they changed it after sending the mail item.", max_length=5)),
                ('lob_letter_object', models.JSONField(blank=True, help_text='If the mail item was sent via Lob, this is the JSON response of the API call that was made to send the mail item, documented at https://lob.com/docs/python#letters.', null=True)),
                ('tracking_number', models.CharField(blank=True, help_text='The USPS tracking number for the mail item.', max_length=100)),
                ('html_content', models.TextField(help_text='The HTML content of the letter at the time it was sent, in English.')),
                ('localized_html_content', models.TextField(blank=True, help_text="The HTML content of the letter at the time it was sent, in the user's locale at the time they sent it. If the user's locale is English, this will be blank (since the English version is already stored in another field).")),
                ('letter_sent_at', models.DateTimeField(blank=True, help_text='When the letter was mailed.', null=True)),
                ('letter_emailed_at', models.DateTimeField(blank=True, help_text='When the letter was e-mailed.', null=True)),
                ('fully_processed_at', models.DateTimeField(blank=True, help_text='When the letter was fully processed, i.e. sent to all relevant parties.', null=True)),
                ('mail_choice', models.TextField(choices=[('WE_WILL_MAIL', 'Yes, have JustFix mail this letter for me.'), ('USER_WILL_MAIL', "No thanks, I'll mail it myself.")], default='WE_WILL_MAIL', help_text='How the letter will be mailed.', max_length=30)),
                ('email_to_landlord', models.BooleanField(blank=True, help_text='Whether to email a copy of the letter to the landlord. Requires a landlord email to be provided', null=True)),
                ('pdf_base64', models.TextField(blank=True, help_text='A base64 encoded string representing the English content of the letter.')),
                ('hash', models.CharField(blank=True, max_length=64, null=True, unique=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
            bases=(models.Model, project.util.lob_django_util.SendableViaLobMixin),
        ),
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_line', models.CharField(blank=True, help_text='Usually the first line of the address, e.g. "150 Court Street"', max_length=64)),
                ('secondary_line', models.CharField(blank=True, help_text='Optional. Usually the second line of the address, e.g. "Suite 2"', max_length=64)),
                ('city', models.CharField(blank=True, help_text='The city of the address, e.g. "Brooklyn".', max_length=80)),
                ('state', models.CharField(blank=True, choices=[('AK', 'Alaska'), ('AL', 'Alabama'), ('AS', 'American Samoa'), ('AZ', 'Arizona'), ('AR', 'Arkansas'), ('CA', 'California'), ('CO', 'Colorado'), ('CT', 'Connecticut'), ('DE', 'Delaware'), ('DC', 'District of Columbia'), ('FL', 'Florida'), ('GA', 'Georgia'), ('GU', 'Guam'), ('HI', 'Hawaii'), ('ID', 'Idaho'), ('IL', 'Illinois'), ('IN', 'Indiana'), ('IA', 'Iowa'), ('KS', 'Kansas'), ('KY', 'Kentucky'), ('LA', 'Louisiana'), ('ME', 'Maine'), ('MD', 'Maryland'), ('MA', 'Massachusetts'), ('MI', 'Michigan'), ('MN', 'Minnesota'), ('MP', 'Northern Mariana Islands'), ('MS', 'Mississippi'), ('MO', 'Missouri'), ('MT', 'Montana'), ('NE', 'Nebraska'), ('NV', 'Nevada'), ('NH', 'New Hampshire'), ('NJ', 'New Jersey'), ('NM', 'New Mexico'), ('NY', 'New York'), ('NC', 'North Carolina'), ('ND', 'North Dakota'), ('OH', 'Ohio'), ('OK', 'Oklahoma'), ('OR', 'Oregon'), ('PA', 'Pennsylvania'), ('PR', 'Puerto Rico'), ('RI', 'Rhode Island'), ('SC', 'South Carolina'), ('SD', 'South Dakota'), ('TN', 'Tennessee'), ('TX', 'Texas'), ('UT', 'Utah'), ('VT', 'Vermont'), ('VA', 'Virginia'), ('VI', 'Virgin Islands'), ('WA', 'Washington'), ('WV', 'West Virginia'), ('WI', 'Wisconsin'), ('WY', 'Wyoming')], help_text='The two-letter state or territory for the address, e.g. "NY".', max_length=2)),
                ('zip_code', models.CharField(blank=True, help_text='The zip code of the address, e.g. "11201" or "94107-2282".', max_length=10, validators=[project.util.mailing_address.ZipCodeValidator()])),
                ('first_name', models.CharField(blank=True, help_text="The user's first/given name.", max_length=100)),
                ('last_name', models.CharField(blank=True, help_text="The user's last/family name.", max_length=100)),
                ('phone_number', models.CharField(blank=True, help_text='A U.S. phone number without parentheses or hyphens, e.g. "5551234567".', max_length=10, validators=[project.util.phone_number.validate_phone_number])),
                ('email', models.EmailField(help_text="The user's email address.", max_length=254)),
                ('bbl', models.CharField(blank=True, help_text="The zero-padded borough, block and lot (BBL) number for the user's home address property.", max_length=10)),
                ('urbanization', models.CharField(blank=True, help_text='Optional. Only used for addresses in Puerto Rico.', max_length=80, null=True)),
                ('letter', models.OneToOneField(help_text='The GCE letter this user is sending to their landlord.', on_delete=django.db.models.deletion.CASCADE, related_name='user_details', to='gceletter.gceletter')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LandlordDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_line', models.CharField(blank=True, help_text='Usually the first line of the address, e.g. "150 Court Street"', max_length=64)),
                ('secondary_line', models.CharField(blank=True, help_text='Optional. Usually the second line of the address, e.g. "Suite 2"', max_length=64)),
                ('city', models.CharField(blank=True, help_text='The city of the address, e.g. "Brooklyn".', max_length=80)),
                ('state', models.CharField(blank=True, choices=[('AK', 'Alaska'), ('AL', 'Alabama'), ('AS', 'American Samoa'), ('AZ', 'Arizona'), ('AR', 'Arkansas'), ('CA', 'California'), ('CO', 'Colorado'), ('CT', 'Connecticut'), ('DE', 'Delaware'), ('DC', 'District of Columbia'), ('FL', 'Florida'), ('GA', 'Georgia'), ('GU', 'Guam'), ('HI', 'Hawaii'), ('ID', 'Idaho'), ('IL', 'Illinois'), ('IN', 'Indiana'), ('IA', 'Iowa'), ('KS', 'Kansas'), ('KY', 'Kentucky'), ('LA', 'Louisiana'), ('ME', 'Maine'), ('MD', 'Maryland'), ('MA', 'Massachusetts'), ('MI', 'Michigan'), ('MN', 'Minnesota'), ('MP', 'Northern Mariana Islands'), ('MS', 'Mississippi'), ('MO', 'Missouri'), ('MT', 'Montana'), ('NE', 'Nebraska'), ('NV', 'Nevada'), ('NH', 'New Hampshire'), ('NJ', 'New Jersey'), ('NM', 'New Mexico'), ('NY', 'New York'), ('NC', 'North Carolina'), ('ND', 'North Dakota'), ('OH', 'Ohio'), ('OK', 'Oklahoma'), ('OR', 'Oregon'), ('PA', 'Pennsylvania'), ('PR', 'Puerto Rico'), ('RI', 'Rhode Island'), ('SC', 'South Carolina'), ('SD', 'South Dakota'), ('TN', 'Tennessee'), ('TX', 'Texas'), ('UT', 'Utah'), ('VT', 'Vermont'), ('VA', 'Virginia'), ('VI', 'Virgin Islands'), ('WA', 'Washington'), ('WV', 'West Virginia'), ('WI', 'Wisconsin'), ('WY', 'Wyoming')], help_text='The two-letter state or territory for the address, e.g. "NY".', max_length=2)),
                ('zip_code', models.CharField(blank=True, help_text='The zip code of the address, e.g. "11201" or "94107-2282".', max_length=10, validators=[project.util.mailing_address.ZipCodeValidator()])),
                ('name', models.CharField(blank=True, help_text="The landlord's name.", max_length=100)),
                ('email', models.EmailField(blank=True, help_text="The landlord's email address.", max_length=254)),
                ('is_looked_up', models.BooleanField(default=False, help_text='Whether the name and address was looked up automatically, or manually entered by the user.')),
                ('urbanization', models.CharField(blank=True, help_text='Optional. Only used for addresses in Puerto Rico.', max_length=80, null=True)),
                ('letter', models.OneToOneField(help_text='The GCE letter being sent to this landlord.', on_delete=django.db.models.deletion.CASCADE, related_name='landlord_details', to='gceletter.gceletter')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
