# Generated by Django 3.2.13 on 2025-08-20 01:06

from django.db import migrations, models
import project.util.lob_django_util
import project.util.phone_number


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GCELetter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail_choice', models.TextField(choices=[('WE_WILL_MAIL', 'Yes, have JustFix mail this letter for me.'), ('USER_WILL_MAIL', "No thanks, I'll mail it myself.")], help_text='How the letter of complaint will be mailed.', max_length=30)),
                ('html_content', models.TextField(blank=True, help_text='The HTML content of the letter at the time it was requested.')),
                ('lob_letter_object', models.JSONField(blank=True, help_text='If the letter was sent via Lob, this is the JSON response of the API call that was made to send the letter, documented at https://lob.com/docs/python#letters.', null=True)),
                ('tracking_number', models.CharField(blank=True, help_text='The tracking number for the letter. Note that when this is changed, the user will be notified via SMS and added to a LOC follow-up campaign, if one has been configured.', max_length=100)),
                ('letter_sent_at', models.DateTimeField(blank=True, help_text='When the letter was mailed through the postal service.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(blank=True, help_text="The user's first/given name.", max_length=100)),
                ('last_name', models.CharField(blank=True, help_text="The user's last/family name.", max_length=100)),
                ('phone_number', models.CharField(blank=True, help_text='A U.S. phone number without parentheses or hyphens, e.g. "5551234567".', max_length=10, validators=[project.util.phone_number.validate_phone_number])),
                ('email', models.EmailField(help_text="The user's email address.", max_length=254)),
                ('bbl', models.CharField(blank=True, help_text="The zero-padded borough, block and lot (BBL) number for the user's home address property.", max_length=10)),
                ('house_number', models.TextField(blank=True, help_text="The user's home address house number.")),
                ('street_name', models.TextField(blank=True, help_text="The user's home address street name.")),
                ('apt_no', models.TextField(blank=True, help_text="The user's home address apartment number (address line 2).")),
                ('borough', models.CharField(blank=True, choices=[('BROOKLYN', 'Brooklyn'), ('QUEENS', 'Queens'), ('BRONX', 'Bronx'), ('MANHATTAN', 'Manhattan'), ('STATEN_ISLAND', 'Staten Island')], help_text="The user's home address borough.", max_length=20)),
                ('zipcode', models.CharField(blank=True, help_text="The user's home address zipcode.", max_length=5)),
                ('ll_full_name', models.CharField(blank=True, help_text="The user's landlord's full name.", max_length=100)),
                ('ll_email', models.EmailField(help_text="The user's email address.", max_length=254)),
                ('ll_house_number', models.TextField(blank=True, help_text="The user's landlord's address house number.")),
                ('ll_street_name', models.TextField(blank=True, help_text="The user's landlord's address street name.")),
                ('ll_apt_no', models.TextField(blank=True, help_text="The user's landlord's address apartment number (address line 2).")),
                ('ll_borough', models.CharField(blank=True, choices=[('BROOKLYN', 'Brooklyn'), ('QUEENS', 'Queens'), ('BRONX', 'Bronx'), ('MANHATTAN', 'Manhattan'), ('STATEN_ISLAND', 'Staten Island')], help_text="The user's landlord's address borough.", max_length=20)),
                ('ll_zipcode', models.CharField(blank=True, help_text="The user's landlord's address zipcode.", max_length=5)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, project.util.lob_django_util.SendableViaLobMixin),
        ),
    ]
