# Generated by Django 3.2.13 on 2025-11-14 20:53

from django.db import migrations, models
import project.util.phone_number


class Migration(migrations.Migration):

    dependencies = [
        ('gceletter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComingSoonNotifyContacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone_number', models.CharField(blank=True, help_text='A U.S. phone number without parentheses or hyphens, e.g. "5551234567".', max_length=10, validators=[project.util.phone_number.validate_phone_number])),
            ],
        ),
    ]
