# Generated by Django 3.2.13 on 2025-08-21 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gceletter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gceletter',
            name='hash',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
