# Generated by Django 3.2.13 on 2025-08-22 21:28

from django.db import migrations, models
import django.db.models.deletion
import project.util.mailing_address
import project.util.phone_number


class Migration(migrations.Migration):

    dependencies = [
        ('gceletter', '0002_gceletter_hash'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gceletter',
            name='apt_no',
        ),
        migrations.RemoveField(
            model_name='gceletter',
            name='bbl',
        ),
        migrations.RemoveField(
            model_name='gceletter',
            name='borough',
        ),
        migrations.RemoveField(
            model_name='gceletter',
            name='email',
        ),
        migrations.RemoveField(
            model_name='gceletter',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='gceletter',
            name='house_number',
        ),
        migrations.RemoveField(
            model_name='gceletter',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='gceletter',
            name='ll_apt_no',
        ),
        migrations.RemoveField(
            model_name='gceletter',
            name='ll_borough',
        ),
        migrations.RemoveField(
            model_name='gceletter',
            name='ll_email',
        ),
        migrations.RemoveField(
            model_name='gceletter',
            name='ll_full_name',
        ),
        migrations.RemoveField(
            model_name='gceletter',
            name='ll_house_number',
        ),
        migrations.RemoveField(
            model_name='gceletter',
            name='ll_street_name',
        ),
        migrations.RemoveField(
            model_name='gceletter',
            name='ll_zipcode',
        ),
        migrations.RemoveField(
            model_name='gceletter',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='gceletter',
            name='street_name',
        ),
        migrations.RemoveField(
            model_name='gceletter',
            name='zipcode',
        ),
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_line', models.CharField(blank=True, help_text='Usually the first line of the address, e.g. "150 Court Street"', max_length=64)),
                ('secondary_line', models.CharField(blank=True, help_text='Optional. Usually the second line of the address, e.g. "Suite 2"', max_length=64)),
                ('city', models.CharField(blank=True, help_text='The city of the address, e.g. "Brooklyn".', max_length=80)),
                ('state', models.CharField(blank=True, choices=[('AK', 'Alaska'), ('AL', 'Alabama'), ('AS', 'American Samoa'), ('AZ', 'Arizona'), ('AR', 'Arkansas'), ('CA', 'California'), ('CO', 'Colorado'), ('CT', 'Connecticut'), ('DE', 'Delaware'), ('DC', 'District of Columbia'), ('FL', 'Florida'), ('GA', 'Georgia'), ('GU', 'Guam'), ('HI', 'Hawaii'), ('ID', 'Idaho'), ('IL', 'Illinois'), ('IN', 'Indiana'), ('IA', 'Iowa'), ('KS', 'Kansas'), ('KY', 'Kentucky'), ('LA', 'Louisiana'), ('ME', 'Maine'), ('MD', 'Maryland'), ('MA', 'Massachusetts'), ('MI', 'Michigan'), ('MN', 'Minnesota'), ('MP', 'Northern Mariana Islands'), ('MS', 'Mississippi'), ('MO', 'Missouri'), ('MT', 'Montana'), ('NE', 'Nebraska'), ('NV', 'Nevada'), ('NH', 'New Hampshire'), ('NJ', 'New Jersey'), ('NM', 'New Mexico'), ('NY', 'New York'), ('NC', 'North Carolina'), ('ND', 'North Dakota'), ('OH', 'Ohio'), ('OK', 'Oklahoma'), ('OR', 'Oregon'), ('PA', 'Pennsylvania'), ('PR', 'Puerto Rico'), ('RI', 'Rhode Island'), ('SC', 'South Carolina'), ('SD', 'South Dakota'), ('TN', 'Tennessee'), ('TX', 'Texas'), ('UT', 'Utah'), ('VT', 'Vermont'), ('VA', 'Virginia'), ('VI', 'Virgin Islands'), ('WA', 'Washington'), ('WV', 'West Virginia'), ('WI', 'Wisconsin'), ('WY', 'Wyoming')], help_text='The two-letter state or territory for the address, e.g. "NY".', max_length=2)),
                ('zip_code', models.CharField(blank=True, help_text='The zip code of the address, e.g. "11201" or "94107-2282".', max_length=10, validators=[project.util.mailing_address.ZipCodeValidator()])),
                ('first_name', models.CharField(blank=True, help_text="The user's first/given name.", max_length=100)),
                ('last_name', models.CharField(blank=True, help_text="The user's last/family name.", max_length=100)),
                ('phone_number', models.CharField(blank=True, help_text='A U.S. phone number without parentheses or hyphens, e.g. "5551234567".', max_length=10, validators=[project.util.phone_number.validate_phone_number])),
                ('email', models.EmailField(help_text="The user's email address.", max_length=254)),
                ('bbl', models.CharField(blank=True, help_text="The zero-padded borough, block and lot (BBL) number for the user's home address property.", max_length=10)),
                ('urbanization', models.CharField(blank=True, help_text='Optional. Only used for addresses in Puerto Rico.', max_length=80, null=True)),
                ('letter', models.OneToOneField(help_text='The GCE letter this user is sending to their landlord.', on_delete=django.db.models.deletion.CASCADE, related_name='user_details', to='gceletter.gceletter')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LandlordDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_line', models.CharField(blank=True, help_text='Usually the first line of the address, e.g. "150 Court Street"', max_length=64)),
                ('secondary_line', models.CharField(blank=True, help_text='Optional. Usually the second line of the address, e.g. "Suite 2"', max_length=64)),
                ('city', models.CharField(blank=True, help_text='The city of the address, e.g. "Brooklyn".', max_length=80)),
                ('state', models.CharField(blank=True, choices=[('AK', 'Alaska'), ('AL', 'Alabama'), ('AS', 'American Samoa'), ('AZ', 'Arizona'), ('AR', 'Arkansas'), ('CA', 'California'), ('CO', 'Colorado'), ('CT', 'Connecticut'), ('DE', 'Delaware'), ('DC', 'District of Columbia'), ('FL', 'Florida'), ('GA', 'Georgia'), ('GU', 'Guam'), ('HI', 'Hawaii'), ('ID', 'Idaho'), ('IL', 'Illinois'), ('IN', 'Indiana'), ('IA', 'Iowa'), ('KS', 'Kansas'), ('KY', 'Kentucky'), ('LA', 'Louisiana'), ('ME', 'Maine'), ('MD', 'Maryland'), ('MA', 'Massachusetts'), ('MI', 'Michigan'), ('MN', 'Minnesota'), ('MP', 'Northern Mariana Islands'), ('MS', 'Mississippi'), ('MO', 'Missouri'), ('MT', 'Montana'), ('NE', 'Nebraska'), ('NV', 'Nevada'), ('NH', 'New Hampshire'), ('NJ', 'New Jersey'), ('NM', 'New Mexico'), ('NY', 'New York'), ('NC', 'North Carolina'), ('ND', 'North Dakota'), ('OH', 'Ohio'), ('OK', 'Oklahoma'), ('OR', 'Oregon'), ('PA', 'Pennsylvania'), ('PR', 'Puerto Rico'), ('RI', 'Rhode Island'), ('SC', 'South Carolina'), ('SD', 'South Dakota'), ('TN', 'Tennessee'), ('TX', 'Texas'), ('UT', 'Utah'), ('VT', 'Vermont'), ('VA', 'Virginia'), ('VI', 'Virgin Islands'), ('WA', 'Washington'), ('WV', 'West Virginia'), ('WI', 'Wisconsin'), ('WY', 'Wyoming')], help_text='The two-letter state or territory for the address, e.g. "NY".', max_length=2)),
                ('zip_code', models.CharField(blank=True, help_text='The zip code of the address, e.g. "11201" or "94107-2282".', max_length=10, validators=[project.util.mailing_address.ZipCodeValidator()])),
                ('name', models.CharField(blank=True, help_text="The landlord's name.", max_length=100)),
                ('email', models.EmailField(blank=True, help_text="The landlord's email address.", max_length=254)),
                ('is_looked_up', models.BooleanField(default=False, help_text='Whether the name and address was looked up automatically, or manually entered by the user.')),
                ('urbanization', models.CharField(blank=True, help_text='Optional. Only used for addresses in Puerto Rico.', max_length=80, null=True)),
                ('letter', models.OneToOneField(help_text='The GCE letter being sent to this landlord.', on_delete=django.db.models.deletion.CASCADE, related_name='landlord_details', to='gceletter.gceletter')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
