"""
Django settings for project project.

Generated by 'django-admin startproject' using Django 2.1.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

from typing import List
import dj_database_url

from . import justfix_environment
from .justfix_environment import BASE_DIR
from .util.settings_util import (
    parse_secure_proxy_ssl_header, LazilyImportedFunction)
from .util import git


env = justfix_environment.get()

SECRET_KEY = env.SECRET_KEY

DEBUG = env.DEBUG

# TODO: Figure out if this can securely stay at '*'.
ALLOWED_HOSTS: List[str] = ['*']


if env.SECURE_PROXY_SSL_HEADER:
    SECURE_PROXY_SSL_HEADER = parse_secure_proxy_ssl_header(
        env.SECURE_PROXY_SSL_HEADER
    )

SECURE_SSL_REDIRECT = env.SECURE_SSL_REDIRECT

SECURE_HSTS_SECONDS = env.SECURE_HSTS_SECONDS

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.sites',
    'whitenoise.runserver_nostatic',
    'django.contrib.staticfiles',
    'graphene_django',
    'project.apps.DefaultConfig',
    'frontend',
    'legacy_tenants.apps.LegacyTenantsConfig',
    'users.apps.UsersConfig',
    'onboarding.apps.OnboardingConfig',
    'issues.apps.IssuesConfig',
    'loc.apps.LocConfig',
    'airtable.apps.AirtableConfig',
    'texting.apps.TextingConfig',
    'nycha.apps.NychaConfig',
    'hpaction.apps.HPActionConfig',
    'twofactor.apps.TwofactorConfig',
    'nycdb'
]

MIDDLEWARE = [
    'project.middleware.CSPHashingMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'twofactor.middleware.admin_requires_2fa_middleware',
]

ROOT_URLCONF = 'project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'frontend.context_processors.safe_mode',
                'project.context_processors.ga_snippet',
                'project.context_processors.facebook_pixel_snippet',
                'project.context_processors.rollbar_snippet',
            ],
        },
    },
]

SITE_ID = 1

WSGI_APPLICATION = 'project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

DATABASES = {
    'default': dj_database_url.parse(env.DATABASE_URL),
}

if env.SPATIALITE_LIBRARY_PATH:
    SPATIALITE_LIBRARY_PATH = env.SPATIALITE_LIBRARY_PATH

NYCDB_DATABASE = None

if env.NYCDB_DATABASE_URL:
    DATABASES['nycdb'] = dj_database_url.parse(env.NYCDB_DATABASE_URL)
    NYCDB_DATABASE = 'nycdb'

MIGRATION_MODULES = {
    # The NYCDB is an external database that we read from, so we don't
    # want to modify its schema in any way.
    'nycdb': None
}


# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTH_USER_MODEL = 'users.JustfixUser'

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'legacy_tenants.auth.LegacyTenantsAppBackend',
]

LOGIN_URL = '/login'

# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# This is based off the default Django logging configuration:
# https://github.com/django/django/blob/master/django/utils/log.py
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'rollbar': {
            # This will be replaced by a real handler if Rollbar is enabled.
            'level': 'ERROR',
            'class': 'logging.NullHandler'
        },
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'debug' if env.LOG_LEVEL == 'DEBUG' else None,
        },
        'django.server': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'filters': ['skip_static_requests'],
            'formatter': 'django.server',
        },
    },
    'filters': {
        'skip_static_requests': {
            '()': 'django.utils.log.CallbackFilter',
            'callback': LazilyImportedFunction(
                'project.logging.skip_static_requests')
        }
    },
    'formatters': {
        'debug': {
            'format': '{levelname}:{name} {message}',
            'style': '{',
        },
        'django.server': {
            '()': 'django.utils.log.ServerFormatter',
            'format': '[{server_time}] {message}',
            'style': '{',
        }
    },
    'loggers': {
        '': {
            'handlers': ['console', 'rollbar'],
            'level': env.LOG_LEVEL,
        },
        'twilio': {
            # At the INFO level, Twilio logs the recipient and
            # body of SMS messages, which we'd like to keep out
            # of production logs, as it's PII, so we'll only
            # log warnings.
            'level': 'WARNING'
        },
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'django.server': {
            'handlers': ['django.server'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

STATIC_URL = '/static/'

_STATIC_ROOT_PATH = BASE_DIR / 'staticfiles'

STATIC_ROOT = str(_STATIC_ROOT_PATH)

# This avoids a spurious warning from whitenoise that
# shows up even in development mode.
_STATIC_ROOT_PATH.mkdir(exist_ok=True)

STATICFILES_STORAGE = 'project.storage.CompressedStaticFilesStorage'

_MEDIA_ROOT_PATH = BASE_DIR / 'mediafiles'

_MEDIA_ROOT_PATH.mkdir(exist_ok=True)

MEDIA_ROOT = str(_MEDIA_ROOT_PATH)

DEFAULT_FILE_STORAGE = 'django.core.files.storage.FileSystemStorage'

if env.AWS_ACCESS_KEY_ID:
    DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'

AWS_ACCESS_KEY_ID = env.AWS_ACCESS_KEY_ID

AWS_SECRET_ACCESS_KEY = env.AWS_SECRET_ACCESS_KEY

AWS_STORAGE_BUCKET_NAME = env.AWS_STORAGE_BUCKET_NAME

AWS_DEFAULT_ACL = 'private'

AWS_BUCKET_ACL = 'private'

AWS_AUTO_CREATE_BUCKET = True

AWS_STORAGE_STATICFILES_BUCKET_NAME = env.AWS_STORAGE_STATICFILES_BUCKET_NAME

AWS_STORAGE_STATICFILES_ORIGIN = (
    f'https://{AWS_STORAGE_STATICFILES_BUCKET_NAME}.s3.amazonaws.com')

GRAPHENE = {
    'SCHEMA': 'project.schema.schema',
    'SCHEMA_INDENT': 2,
    # Setting this to None is very important for error logging, as
    # its default value of
    # graphene_django.debug.middleware.DjangoDebugMiddleware somehow
    # silently eats all errors:
    #
    #   https://github.com/graphql-python/graphene-django/issues/504
    'MIDDLEWARE': None
}

GEOCODING_SEARCH_URL = "https://geosearch.planninglabs.nyc/v1/search"

GEOCODING_TIMEOUT = 3

LANDLORD_LOOKUP_URL = "https://whoownswhat.justfix.nyc/api/landlord"

LANDLORD_LOOKUP_TIMEOUT = GEOCODING_TIMEOUT

LEGACY_MONGODB_URL = env.LEGACY_MONGODB_URL

LEGACY_ORIGIN = env.LEGACY_ORIGIN

GA_TRACKING_ID = env.GA_TRACKING_ID

FACEBOOK_PIXEL_ID = env.FACEBOOK_PIXEL_ID

GIT_INFO = git.GitInfo.from_dir_or_env(BASE_DIR)

TWILIO_ACCOUNT_SID = env.TWILIO_ACCOUNT_SID

TWILIO_AUTH_TOKEN = env.TWILIO_AUTH_TOKEN

TWILIO_PHONE_NUMBER = env.TWILIO_PHONE_NUMBER

TWILIO_TIMEOUT = 3

SLACK_WEBHOOK_URL = env.SLACK_WEBHOOK_URL

SLACK_TIMEOUT = 3

AIRTABLE_API_KEY = env.AIRTABLE_API_KEY

AIRTABLE_URL = env.AIRTABLE_URL

AIRTABLE_TIMEOUT = 3

HP_ACTION_API_ENDPOINT = env.HP_ACTION_API_ENDPOINT

HP_ACTION_TEMPLATE_ID = env.HP_ACTION_TEMPLATE_ID

HP_ACTION_CUSTOMER_KEY = env.HP_ACTION_CUSTOMER_KEY

HP_ACTION_TIMEOUT = 90

TWOFACTOR_VERIFY_DURATION = env.TWOFACTOR_VERIFY_DURATION

# If this is truthy, Rollbar will be enabled on the client-side.
ROLLBAR_ACCESS_TOKEN = env.ROLLBAR_ACCESS_TOKEN

if env.ROLLBAR_SERVER_ACCESS_TOKEN:
    # The following will enable Rollbar on the server-side.
    ROLLBAR = {
        'access_token': env.ROLLBAR_SERVER_ACCESS_TOKEN,
        'environment': 'development' if DEBUG else 'production',
        'code_version': GIT_INFO.get_version_str(),
        'root': str(BASE_DIR),
    }
    LOGGING['handlers']['rollbar'].update({    # type: ignore
        'class': 'rollbar.logger.RollbarHandler'
    })
    MIDDLEWARE.append(
        'rollbar.contrib.django.middleware.RollbarNotifierMiddlewareExcluding404')

CSP_STYLE_SRC = [
    "'self'",
    # We originally disallowed unsafe-inline, but it just became too much of
    # a hassle, as third-party libraries injected inline styles and
    # even SVGs used in <img> tags were unable to contain <style> elements
    # too.
    "'unsafe-inline'"
]

CSP_IMG_SRC = [
    "'self'",
]

CSP_SCRIPT_SRC = [
    "'self'",
]

CSP_CONNECT_SRC = [
    "'self'",
    "https://geosearch.planninglabs.nyc"
]

if AWS_STORAGE_STATICFILES_BUCKET_NAME:
    STATICFILES_STORAGE = 'project.storage.S3StaticFilesStorage'
    STATIC_URL = f'{AWS_STORAGE_STATICFILES_ORIGIN}/'
    CSP_STYLE_SRC.append(AWS_STORAGE_STATICFILES_ORIGIN)
    CSP_SCRIPT_SRC.append(AWS_STORAGE_STATICFILES_ORIGIN)
    CSP_IMG_SRC.append(AWS_STORAGE_STATICFILES_ORIGIN)

if DEBUG:
    CSP_EXCLUDE_URL_PREFIXES = (
        # The webpack-bundle-analyzer report contains inline JS
        # that we need to permit if we want to use it, so
        # allow it during development.
        f'{STATIC_URL}frontend/report.html',
        # Bleh, the GraphIQL UI has a bunch of inline script code.
        '/graphiql',
    )
