# Generated by Django 2.2.13 on 2020-08-17 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nycha', '0003_auto_20200404_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='nychaproperty',
            name='development',
            field=models.CharField(default='UNKNOWN', help_text='The development name of the NYCHA property.', max_length=255),
            preserve_default=False,
        ),
    ]
