# Generated by Django 2.2.9 on 2020-02-13 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RapidproRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flow_uuid', models.CharField(max_length=36)),
                ('flow_name', models.CharField(max_length=255)),
                ('user_uuid', models.CharField(max_length=36)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('num_steps', models.IntegerField()),
                ('exit_type', models.CharField(max_length=15)),
                ('num_error_steps', models.IntegerField(null=True)),
                ('was_rent_history_received', models.BooleanField(null=True)),
            ],
        ),
    ]
