# Generated by Django 2.2.10 on 2020-02-19 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dwh', '0002_onlinerenthistoryrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='LetterOfComplaintRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('mail_choice', models.CharField(max_length=30)),
                ('letter_sent_at', models.DateTimeField(blank=True, null=True)),
                ('landlord_responded_by', models.DateTimeField(blank=True, null=True)),
                ('landlord_did_not_respond_by', models.DateTimeField(blank=True, null=True)),
                ('landlord_retaliated_by', models.DateTimeField(blank=True, null=True)),
                ('repairs_made_by', models.DateTimeField(blank=True, null=True)),
                ('interested_in_hp_action_by', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
