# Generated by Django 2.2.9 on 2020-02-24 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('sid', models.CharField(max_length=34, primary_key=True, serialize=False)),
                ('body', models.TextField()),
                ('status', models.CharField(max_length=20)),
                ('date_created', models.DateTimeField()),
                ('date_sent', models.DateTimeField(blank=True, null=True)),
                ('date_updated', models.DateTimeField()),
                ('direction', models.CharField(max_length=15)),
                ('from_number', models.CharField(max_length=15)),
                ('to_number', models.CharField(max_length=15)),
                ('error_code', models.CharField(blank=True, max_length=20, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
