# Generated by Django 2.2.10 on 2020-03-03 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texting_history', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='body',
            field=models.TextField(blank=True),
        ),
    ]
