# Generated by Django 2.2.10 on 2020-03-05 02:28

from django.db import migrations, models
from django.conf import settings

from texting.twilio import tendigit_to_e164


class Migration(migrations.Migration):

    dependencies = [
        ('texting_history', '0003_auto_20200303_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='our_phone_number',
            field=models.CharField(default=tendigit_to_e164(settings.TWILIO_PHONE_NUMBER), max_length=15),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['our_phone_number'], name='texting_his_our_pho_ab8db9_idx'),
        ),
    ]
