# Generated by Django 2.2.10 on 2020-03-12 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texting_history', '0004_auto_20200305_0228'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['user_phone_number', 'ordering'], name='texting_his_user_ph_e51978_idx'),
        ),
    ]
