# Generated by Django 3.2.13 on 2024-12-04 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoodCauseEvictionScreenerResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bbl', models.CharField(help_text='The zero-padded borough, block and lot (BBL) number for the search address property.', max_length=10)),
                ('house_number', models.TextField()),
                ('street_name', models.TextField()),
                ('borough', models.CharField(choices=[('BROOKLYN', 'Brooklyn'), ('QUEENS', 'Queens'), ('BRONX', 'Bronx'), ('MANHATTAN', 'Manhattan'), ('STATEN_ISLAND', 'Staten Island')], max_length=20)),
                ('zipcode', models.CharField(max_length=5)),
                ('address_confirmed', models.BooleanField(default=False, help_text='Whether the user has clicked to confirm the search address is correct.')),
                ('nycdb_results', models.JSONField(blank=True, help_text='Response from the WOW gce/screener API for the search address. Schema may change over time.', null=True)),
                ('form_answers_initial', models.JSONField(blank=True, help_text='The initial set of user responses to the survey form saved on submission, before taking and necessary next steps to confirm criteria.', null=True)),
                ('result_coverage_initial', models.TextField(blank=True, choices=[('COVERED', 'Covered by GCE'), ('NOT_COVERED', 'Not covered by GCE'), ('UNKNOWN', 'Unknown if covered by GCE')], help_text='The initial GCE coverage result based on building data and user form responses, before taking any necessary next steps to confirm criteria.', null=True)),
                ('result_criteria_initial', models.JSONField(blank=True, help_text='An object with each GCE criteria and the initial eligibility determination (eligible, ineligible, unknown), before taking any next steps to confirm criteria.', null=True)),
                ('form_answers_final', models.JSONField(blank=True, help_text='The final set of user responses to the survey form saved on submission, after taking any necessary next steps to confirm criteria.', null=True)),
                ('result_coverage_final', models.TextField(blank=True, choices=[('COVERED', 'Covered by GCE'), ('NOT_COVERED', 'Not covered by GCE'), ('UNKNOWN', 'Unknown if covered by GCE')], help_text='The final GCE coverage result taking into account any confirmed criteria from next steps.', null=True)),
                ('result_criteria_final', models.JSONField(blank=True, help_text='An object with each GCE criteria and the final eligibility determination (eligible, ineligible, unknown), after taking any next steps to confirm criteria.', null=True)),
            ],
        ),
    ]
