# Generated by Django 3.2.13 on 2025-01-03 21:25

from django.db import migrations, models
import project.util.phone_number


class Migration(migrations.Migration):

    dependencies = [
        ('gce', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodcauseevictionscreenerresponse',
            name='phone_number',
            field=models.CharField(blank=True, help_text='A U.S. phone number without parentheses or hyphens, e.g. "5551234567".', max_length=10, validators=[project.util.phone_number.validate_phone_number]),
        ),
    ]
