# Generated by Django 3.2.13 on 2025-03-13 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gce', '0003_auto_20250122_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodcauseevictionscreenerresponse',
            name='result_coverage_final',
            field=models.TextField(blank=True, choices=[('COVERED', 'Covered by Good Cause'), ('NOT_COVERED', 'Not covered by Good Cause'), ('UNKNOWN', 'Unknown if covered by Good Cause'), ('RENT_STABILIZED', 'Rent stabilized, not covered by Good Cause'), ('NYCHA', 'NYCHA, not covered by Good Cause'), ('SUBSIDIZED', 'Subsidized, not covered by Good Cause')], help_text='The final GCE coverage result taking into account any confirmed criteria from next steps.', null=True),
        ),
        migrations.AlterField(
            model_name='goodcauseevictionscreenerresponse',
            name='result_coverage_initial',
            field=models.TextField(blank=True, choices=[('COVERED', 'Covered by Good Cause'), ('NOT_COVERED', 'Not covered by Good Cause'), ('UNKNOWN', 'Unknown if covered by Good Cause'), ('RENT_STABILIZED', 'Rent stabilized, not covered by Good Cause'), ('NYCHA', 'NYCHA, not covered by Good Cause'), ('SUBSIDIZED', 'Subsidized, not covered by Good Cause')], help_text='The initial GCE coverage result based on building data and user form responses, before taking any necessary next steps to confirm criteria.', null=True),
        ),
    ]
