# Generated by Django 3.2.13 on 2025-04-18 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gce', '0004_auto_20250313_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodcauseevictionscreenerresponse',
            name='bbl',
            field=models.CharField(blank=True, help_text='The zero-padded borough, block and lot (BBL) number for the search address property.', max_length=10),
        ),
        migrations.AlterField(
            model_name='goodcauseevictionscreenerresponse',
            name='borough',
            field=models.CharField(blank=True, choices=[('BROOKLYN', 'Brooklyn'), ('QUEENS', 'Queens'), ('BRONX', 'Bronx'), ('MANHATTAN', 'Manhattan'), ('STATEN_ISLAND', 'Staten Island')], max_length=20),
        ),
        migrations.AlterField(
            model_name='goodcauseevictionscreenerresponse',
            name='house_number',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='goodcauseevictionscreenerresponse',
            name='street_name',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='goodcauseevictionscreenerresponse',
            name='zipcode',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
