# Generated by Django 2.1.7 on 2019-03-27 11:42

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmittedForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('form_class', models.CharField(help_text="The fully-qualified dotted name of the class for the form, e.g. 'onboarding.forms.OnboardingStep1Form'.", max_length=500)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(help_text='The data submitted to the form.')),
                ('is_valid', models.BooleanField(help_text='Whether the form is valid (i.e., it has no validation errors).')),
                ('user', models.ForeignKey(help_text='The user who submitted the form, if any.', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
