# Generated by Django 2.2.13 on 2020-10-23 12:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerOrg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the partner organization.', max_length=150, unique=True)),
                ('slug', models.SlugField(help_text='The short identifier for the partner organization.', max_length=20, unique=True)),
                ('website', models.URLField(help_text='The primary website of the partner organization.')),
                ('users', models.ManyToManyField(blank=True, help_text='Users whose details the partner organization has access to.', related_name='partner_orgs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
