from pathlib import Path
from django.core.management.base import BaseCommand

from project.justfix_environment import BASE_DIR
from hpaction.hotdocs_cmp import HDComponentLibrary
from hpaction.codegen import PythonCodeGenerator


MASTER_CMP_PATH = BASE_DIR / 'hpaction' / 'hotdocs-data' / 'Master.cmp'


class Command(BaseCommand):
    help = f"Parse {MASTER_CMP_PATH.name} and show results."

    def handle(self, *args, **options) -> None:
        lib = HDComponentLibrary(MASTER_CMP_PATH)

        OUTPUT_PATH = BASE_DIR / "hpactionvars.py"

        print(f"Outputting Python code to {OUTPUT_PATH}.")

        code = PythonCodeGenerator(lib, "HPActionVariables")
        cmd = Path(__file__).stem
        OUTPUT_PATH.write_text(
            f'# This code was generated by the "{cmd}" Django management command.\n\n' +
            code.getvalue()
        )
