import datetime
from typing import List
import pydantic
from django import forms
from django.conf import settings
from django.core.exceptions import ValidationError

from . import models
from .views import render_letter_body
from project import common_data


class AccessDatesValidation(pydantic.BaseModel):
    MIN_DAYS: int
    MIN_DAYS_TEXT: str


class AccessDatesForm(forms.Form):
    NUM_DATE_FIELDS = 3

    date1 = forms.DateField(required=True)

    date2 = forms.DateField(required=False)

    date3 = forms.DateField(required=False)

    def clean(self):
        dates = self.get_cleaned_dates(super().clean())
        if len(dates) != len(set(dates)):
            raise ValidationError('Please ensure all the dates are different.')
        self._validate_minimum_dates(dates)

    def _validate_minimum_dates(self, dates: List[datetime.date]):
        cfg = AccessDatesValidation(**common_data.load_json('access-dates-validation.json'))
        today = datetime.date.today()
        for date in dates:
            if (date - today).days < cfg.MIN_DAYS:
                raise ValidationError(
                    f'Please ensure all dates are at least {cfg.MIN_DAYS_TEXT} from today.')

    def get_cleaned_dates(self, cleaned_data=None) -> List[datetime.date]:
        if cleaned_data is None:
            cleaned_data = self.cleaned_data
        result = []
        for i in range(self.NUM_DATE_FIELDS):
            date = cleaned_data.get(f'date{i + 1}')
            if date is not None:
                result.append(date)
        return result


class LandlordDetailsForm(forms.ModelForm):
    class Meta:
        model = models.LandlordDetails
        fields = ('name', 'address')


class LetterRequestForm(forms.ModelForm):
    class Meta:
        model = models.LetterRequest
        fields = ('mail_choice',)

    def clean(self):
        super().clean()

        header = (
            f'<!-- This HTML was generated by {self.__class__.__name__} on '
            f'{datetime.datetime.now()} using git revision '
            f'{settings.GIT_INFO.get_version_str()}. -->\n'
        )
        self.instance.html_content = header + render_letter_body(self.instance.user)
