# Generated by Django 2.1 on 2018-09-05 23:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OnboardingInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address', models.CharField(help_text="The user's address. Only street name and number are required.", max_length=200)),
                ('address_verified', models.BooleanField(help_text="Whether we've verified, on the server-side, that the user's address is valid.")),
                ('borough', models.CharField(choices=[('BROOKLYN', 'Brooklyn'), ('QUEENS', 'Queens'), ('BRONX', 'Bronx'), ('MANHATTAN', 'Manhattan'), ('STATEN_ISLAND', 'Staten Island')], help_text="The New York City borough the user's address is in.", max_length=20)),
                ('apt_number', models.CharField(max_length=10)),
                ('is_in_eviction', models.BooleanField(help_text='Has the user received an eviction notice?')),
                ('needs_repairs', models.BooleanField(help_text='Does the user need repairs in their apartment?')),
                ('has_no_services', models.BooleanField(help_text='Is the user missing essential services like water?')),
                ('has_pests', models.BooleanField(help_text='Does the user have pests like rodents or bed bugs?')),
                ('has_called_311', models.BooleanField(help_text='Has the user called 311 before?')),
                ('lease_type', models.CharField(choices=[('RENT_STABILIZED', 'Rent Stabilized'), ('MARKET_RATE', 'Market Rate'), ('NYCHA', 'NYCHA'), ('MITCHELL_LAMA', 'Mitchell Lama'), ('COOP', 'COOP'), ('NO_LEASE', 'No Lease'), ('SHELTER', 'Shelter'), ('NOT_SURE', "I'm not sure"), ('OTHER', 'Other')], help_text='The type of lease the user has on their dwelling.', max_length=30)),
                ('receives_public_assistance', models.BooleanField(help_text='Does the user receive public assistance, e.g. Section 8?')),
                ('can_we_sms', models.BooleanField(help_text='Whether we can contact the user via SMS to follow up.')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_info', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
