# Generated by Django 2.1 on 2018-09-25 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onboardinginfo',
            name='lease_type',
            field=models.CharField(choices=[('RENT_STABILIZED', 'Rent Stabilized'), ('MARKET_RATE', 'Market Rate'), ('NYCHA', 'NYCHA'), ('NOT_SURE', "I'm not sure"), ('OTHER', 'Other')], help_text='The type of lease the user has on their dwelling.', max_length=30),
        ),
    ]
