# Generated by Django 2.1.2 on 2018-10-17 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0003_auto_20181004_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='onboardinginfo',
            name='zipcode',
            field=models.CharField(blank=True, help_text="The user's ZIP code.", max_length=12),
        ),
    ]
