# Generated by Django 2.1.2 on 2018-11-26 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0004_onboardinginfo_zipcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='onboardinginfo',
            name='signup_intent',
            field=models.CharField(choices=[('LOC', 'Letter of complaint'), ('HP', 'HP action')], default='LOC', help_text='The reason the user originally signed up with us.', max_length=30),
            preserve_default=False,
        ),
    ]
