# Generated by Django 2.1.2 on 2018-10-29 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0004_onboardinginfo_zipcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='onboardinginfo',
            name='finish_cta_reminder_sent_at',
            field=models.DateField(blank=True, help_text='When, if ever, did we send the user a text message reminding them to finish the call-to-action they signed up for?', null=True),
        ),
    ]
