# Generated by Django 2.1.7 on 2019-03-26 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0006_onboardinginfo_pad_bbl'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddressWithoutBoroughDiagnostic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
