# Generated by Django 2.2.10 on 2020-04-07 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0010_auto_20200326_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onboardinginfo',
            name='has_called_311',
            field=models.BooleanField(blank=True, help_text='Has the user called 311 before?', null=True),
        ),
        migrations.AlterField(
            model_name='onboardinginfo',
            name='has_no_services',
            field=models.BooleanField(blank=True, help_text='Is the user missing essential services like water?', null=True),
        ),
        migrations.AlterField(
            model_name='onboardinginfo',
            name='has_pests',
            field=models.BooleanField(blank=True, help_text='Does the user have pests like rodents or bed bugs?', null=True),
        ),
        migrations.AlterField(
            model_name='onboardinginfo',
            name='is_in_eviction',
            field=models.BooleanField(blank=True, help_text='Has the user received an eviction notice?', null=True),
        ),
        migrations.AlterField(
            model_name='onboardinginfo',
            name='needs_repairs',
            field=models.BooleanField(blank=True, help_text='Does the user need repairs in their apartment?', null=True),
        ),
    ]
