# Generated by Django 2.2.10 on 2020-04-21 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0012_auto_20200418_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onboardinginfo',
            name='signup_intent',
            field=models.CharField(choices=[('LOC', 'Letter of Complaint'), ('HP', 'HP Action'), ('EHP', 'Emergency HP Action'), ('NORENT', 'No rent letter')], help_text='The reason the user originally signed up with us.', max_length=30),
        ),
    ]
