# Generated by Django 2.2.10 on 2020-04-24 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0013_auto_20200421_0135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onboardinginfo',
            name='apt_number',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
