# Generated by Django 2.2.10 on 2020-04-28 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0014_auto_20200424_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='onboardinginfo',
            name='agreed_to_justfix_terms',
            field=models.BooleanField(
                # We're setting the default to True but not preserving it as the
                # ongoing default b/c we want all existing OnboardingInfo models,
                # which represent JustFix.nyc users who have agreed to the TOS and
                # privacy policy, to have the value set to True. This is effectively
                # a data migration.
                default=True,
                help_text='Whether the user has agreed to the JustFix.nyc terms of service and privacy policy.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='onboardinginfo',
            name='agreed_to_norent_terms',
            field=models.BooleanField(default=False, help_text='Whether the user has agreed to the NoRent.org terms of service and privacy policy.'),
        ),
        migrations.AddField(
            model_name='onboardinginfo',
            name='can_receive_rttc_comms',
            field=models.NullBooleanField(help_text='Whether the user has opted-in to being contacted by the Right to the City Alliance (RTTC).'),
        ),
    ]
