# Generated by Django 2.2.10 on 2020-04-28 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0015_agree_to_terms_and_rttc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onboardinginfo',
            name='agreed_to_justfix_terms',
            # Now that all existing JustFix.nyc users have this field set to
            # True from the last migration, we'll default this field to False
            # going forward, since users might onboard via either JustFix.nyc
            # or NoRent.org.
            field=models.BooleanField(default=False, help_text='Whether the user has agreed to the JustFix.nyc terms of service and privacy policy.'),
        ),
    ]
