# Generated by Django 2.2.13 on 2020-08-26 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0016_default_agreed_to_justfix_terms_to_false'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addresswithoutboroughdiagnostic',
            name='address',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='onboardinginfo',
            name='address',
            field=models.CharField(help_text="The user's address. Only street name and number are required.", max_length=64),
        ),
    ]
