# Generated by Django 2.2.13 on 2020-10-05 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0017_auto_20200826_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='onboardinginfo',
            name='can_receive_saje_comms',
            field=models.NullBooleanField(help_text='Whether the user has opted-in to being contacted by Strategic Actions for a Just Economy (SAJE).'),
        ),
    ]
