# Generated by Django 2.2.13 on 2021-01-19 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0018_onboardinginfo_can_receive_saje_comms'),
    ]

    operations = [
        migrations.AddField(
            model_name='onboardinginfo',
            name='agreed_to_evictionfree_terms',
            field=models.BooleanField(default=False, help_text='Whether the user has agreed to the Eviction Free terms of service and privacy policy.'),
        ),
        migrations.AlterField(
            model_name='onboardinginfo',
            name='signup_intent',
            field=models.CharField(choices=[('LOC', 'Letter of Complaint'), ('HP', 'HP Action'), ('EHP', 'Emergency HP Action'), ('NORENT', 'No rent letter'), ('EVICTIONFREE', 'Eviction free')], help_text='The reason the user originally signed up with us.', max_length=30),
        ),
    ]
