# Generated by Django 2.2.13 on 2021-01-26 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0019_auto_20210119_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='onboardinginfo',
            name='can_hj4a_sms',
            field=models.BooleanField(default=False, help_text='Whether Housing Justice for All can contact the user via SMS.'),
        ),
        migrations.AddField(
            model_name='onboardinginfo',
            name='can_rtc_sms',
            field=models.BooleanField(default=False, help_text='Whether the Right to Counsel NYC Coalition can contact the user via SMS.'),
        ),
    ]
