# Generated by Django 2.2.18 on 2021-02-19 21:00

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0020_auto_20210126_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='onboardinginfo',
            name='geometry',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text="The GeoJSON point representing the user's address, if available.", null=True),
        ),
    ]
