# Generated by Django 2.2.18 on 2021-02-22 12:07

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0020_auto_20210126_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='onboardinginfo',
            name='geocoded_address',
            field=models.CharField(blank=True, help_text="This is the user's definitive street address returned by the geocoder, and what the user's latitude, longitude, and other attributes are based from. This should not be very different from the address field (if it is, you may need to change the address so the geocoder matches to the proper location).", max_length=255),
        ),
        migrations.AddField(
            model_name='onboardinginfo',
            name='geometry',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text="The GeoJSON point representing the user's address, if available.", null=True),
        ),
    ]
