# Generated by Django 2.2.18 on 2021-03-09 20:22

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0021_auto_20210222_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='onboardinginfo',
            name='geocoded_point',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, help_text="The point representing the user's address, if available.", null=True, srid=4326),
        ),
    ]
