# Generated by Django 3.2 on 2021-07-07 19:26

from django.db import migrations


def change_other_housing_type_to_not_sure(apps, schema_editor):
    OnboardingInfo = apps.get_model("onboarding", "OnboardingInfo")
    print(len(OnboardingInfo.objects.filter(lease_type="OTHER")))
    for user in OnboardingInfo.objects.filter(lease_type="OTHER"):
        user.lease_type = "NOT_SURE"
        user.save()


class Migration(migrations.Migration):

    dependencies = [
        ("onboarding", "0024_alter_onboardinginfo_address_verified"),
    ]

    operations = [
        migrations.RunPython(
            change_other_housing_type_to_not_sure,
        )
    ]
