# Generated by Django 3.2.4 on 2021-08-03 19:32

from django.db import migrations


def change_legacy_rent_stabilized_housing_type_to_joint_stabilized_controlled_type(
    apps, schema_editor
):
    OnboardingInfo = apps.get_model("onboarding", "OnboardingInfo")
    for user in OnboardingInfo.objects.filter(lease_type="RENT_STABILIZED"):
        user.lease_type = "RENT_STABILIZED_OR_CONTROLLED"
        user.save()

class Migration(migrations.Migration):

    dependencies = [
        ("onboarding", "0026_alter_onboardinginfo_lease_type"),
    ]

    operations = [
        migrations.RunPython(
            change_legacy_rent_stabilized_housing_type_to_joint_stabilized_controlled_type,
        )
    ]
