# Generated by Django 3.2.4 on 2021-08-03 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("onboarding", "0027_auto_20210803_1932"),
    ]

    operations = [
        migrations.AlterField(
            model_name="onboardinginfo",
            name="lease_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("RENT_STABILIZED", "Rent Stabilized"),
                    ("RENT_CONTROLLED", "Rent Controlled"),
                    ("OTHER_AFFORDABLE", "Affordable housing (other than rent-stabilized)"),
                    ("MARKET_RATE", "Market Rate"),
                    ("NYCHA", "NYCHA/Public Housing"),
                    ("NOT_SURE", "I'm not sure"),
                    ("NO_LEASE", "I don't have a lease"),
                    (
                        "RENT_STABILIZED_OR_CONTROLLED",
                        "Either Rent Stabilized or Rent Controlled (legacy option)",
                    ),
                ],
                help_text="The type of housing the user lives in (NYC only).",
                max_length=30,
            ),
        ),
    ]
