# Generated by Django 3.2.5 on 2021-11-29 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0028_alter_onboardinginfo_lease_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onboardinginfo',
            name='signup_intent',
            field=models.CharField(choices=[('LOC', 'Letter of Complaint'), ('HP', 'HP Action'), ('EHP', 'Emergency HP Action'), ('NORENT', 'No rent letter'), ('EVICTIONFREE', 'Eviction free'), ('LALETTERBUILDER', 'LA Letter Builder')], help_text='The reason the user originally signed up with us.', max_length=30),
        ),
    ]
