# Generated by Django 3.2.13 on 2023-07-26 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0030_onboardinginfo_agreed_to_lalatterbuilder_terms_squashed_0031_rename_agreed_to_lalatterbuilder_terms_onboardinginfo_agreed_to_laletterbuilder_terms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onboardinginfo',
            name='signup_intent',
            field=models.CharField(choices=[('LOC', 'Letter of Complaint'), ('HP', 'HP Action'), ('EHP', 'Emergency HP Action'), ('NORENT', 'No rent letter'), ('EVICTIONFREE', 'Eviction free'), ('LALETTERBUILDER', 'LA Tenant Action Center')], help_text='The reason the user originally signed up with us.', max_length=30),
        ),
    ]
