# Generated by Django 3.2.13 on 2025-08-19 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0031_auto_20241023_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='onboardinginfo',
            name='agreed_to_lettersender_terms',
            field=models.BooleanField(default=False, help_text='Whether the user has agreed to the Letter Sender terms of service and privacy policy.'),
        ),
        migrations.AlterField(
            model_name='onboardinginfo',
            name='signup_intent',
            field=models.CharField(choices=[('LOC', 'Letter of Complaint'), ('HP', 'HP Action'), ('EHP', 'Emergency HP Action'), ('NORENT', 'No rent letter'), ('EVICTIONFREE', 'Eviction free'), ('LALETTERBUILDER', 'LA Tenant Action Center'), ('LETTERSENDER', 'GCE Letter Sender')], help_text='The reason the user originally signed up with us.', max_length=30),
        ),
    ]
