# Generated by Django 3.2.13 on 2025-08-20 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0032_auto_20250820_0343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onboardinginfo',
            name='agreed_to_lettersender_terms',
        ),
    ]
