// This file was auto-generated by commondatabuilder.
// Please don't edit it.

export enum BoroughChoice {
  BROOKLYN = "BROOKLYN",
  QUEENS = "QUEENS",
  BRONX = "BRONX",
  MANHATTAN = "MANHATTAN",
  STATEN_ISLAND = "STATEN_ISLAND",
}

export type BoroughChoiceLabels = {
  [k in BoroughChoice]: string;
};

export function getBoroughChoiceLabels(): BoroughChoiceLabels {
  return {
    BROOKLYN: "Brooklyn",
    QUEENS: "Queens",
    BRONX: "Bronx",
    MANHATTAN: "Manhattan",
    STATEN_ISLAND: "Staten Island",
  };
}
