// This file was auto-generated by commondatabuilder.
// Please don't edit it.

export type EvictionFreeUnsupportedLocaleChoice = "ht";

export const EvictionFreeUnsupportedLocaleChoices: EvictionFreeUnsupportedLocaleChoice[] = [
  "ht"
];

const EvictionFreeUnsupportedLocaleChoiceSet: Set<String> = new Set(EvictionFreeUnsupportedLocaleChoices);

export function isEvictionFreeUnsupportedLocaleChoice(choice: string): choice is EvictionFreeUnsupportedLocaleChoice {
  return EvictionFreeUnsupportedLocaleChoiceSet.has(choice);
}
