// This file was auto-generated by commondatabuilder.
// Please don't edit it.

export type HPActionChoice = "NORMAL"|"EMERGENCY";

export const HPActionChoices: HPActionChoice[] = [
  "NORMAL",
  "EMERGENCY"
];

const HPActionChoiceSet: Set<String> = new Set(HPActionChoices);

export function isHPActionChoice(choice: string): choice is HPActionChoice {
  return HPActionChoiceSet.has(choice);
}
