// This file was auto-generated by commondatabuilder.
// Please don't edit it.

export type IncomeFrequencyChoice = "WEEKLY"|"EVERY_TWO_WEEKS"|"MONTHLY";

export const IncomeFrequencyChoices: IncomeFrequencyChoice[] = [
  "WEEKLY",
  "EVERY_TWO_WEEKS",
  "MONTHLY"
];

const IncomeFrequencyChoiceSet: Set<String> = new Set(IncomeFrequencyChoices);

export function isIncomeFrequencyChoice(choice: string): choice is IncomeFrequencyChoice {
  return IncomeFrequencyChoiceSet.has(choice);
}

export type IncomeFrequencyChoiceLabels = {
  [k in IncomeFrequencyChoice]: string;
};

export function getIncomeFrequencyChoiceLabels(): IncomeFrequencyChoiceLabels {
  return {
    WEEKLY: "Weekly",
    EVERY_TWO_WEEKS: "Every two weeks",
    MONTHLY: "Monthly",
  };
}
