// This file was auto-generated by commondatabuilder.
// Please don't edit it.

export type LaIssueAreaChoice = "HEALTH"|"UTILITIES"|"BUILDING_AND_SAFETY";

export const LaIssueAreaChoices: LaIssueAreaChoice[] = [
  "HEALTH",
  "UTILITIES",
  "BUILDING_AND_SAFETY"
];

const LaIssueAreaChoiceSet: Set<String> = new Set(LaIssueAreaChoices);

export function isLaIssueAreaChoice(choice: string): choice is LaIssueAreaChoice {
  return LaIssueAreaChoiceSet.has(choice);
}

export type LaIssueAreaChoiceLabels = {
  [k in LaIssueAreaChoice]: string;
};

export function getLaIssueAreaChoiceLabels(): LaIssueAreaChoiceLabels {
  return {
    HEALTH: "Health",
    UTILITIES: "Utilities",
    BUILDING_AND_SAFETY: "Building and safety",
  };
}
