// This file was auto-generated by commondatabuilder.
// Please don't edit it.

import { t } from "@lingui/macro";
import { li18n } from '../frontend/lib/i18n-lingui';

export type LaIssueChoice = "HEALTH__MOLD__BEDROOM"|"HEALTH__MOLD__KITCHEN"|"HEALTH__PEELING_PAINT__BEDROOM"|"HEALTH__PEELING_PAINT__KITCHEN"|"HEALTH__RODENT_INFESTATION__BEDROOM"|"HEALTH__RODENT_INFESTATION__KITCHEN"|"UTILITIES__DEFECTIVE_ELECTRICITY__BEDROOM"|"UTILITIES__DEFECTIVE_ELECTRICITY__KITCHEN"|"UTILITIES__WATER_LEAK__BEDROOM"|"UTILITIES__WATER_LEAK__KITCHEN"|"BUILDING_AND_SAFETY__HOLES__BEDROOM"|"BUILDING_AND_SAFETY__HOLES__KITCHEN"|"BUILDING_AND_SAFETY__BROKEN_LOCKS__BEDROOM"|"BUILDING_AND_SAFETY__BROKEN_LOCKS__KITCHEN";

export const LaIssueChoices: LaIssueChoice[] = [
  "HEALTH__MOLD__BEDROOM",
  "HEALTH__MOLD__KITCHEN",
  "HEALTH__PEELING_PAINT__BEDROOM",
  "HEALTH__PEELING_PAINT__KITCHEN",
  "HEALTH__RODENT_INFESTATION__BEDROOM",
  "HEALTH__RODENT_INFESTATION__KITCHEN",
  "UTILITIES__DEFECTIVE_ELECTRICITY__BEDROOM",
  "UTILITIES__DEFECTIVE_ELECTRICITY__KITCHEN",
  "UTILITIES__WATER_LEAK__BEDROOM",
  "UTILITIES__WATER_LEAK__KITCHEN",
  "BUILDING_AND_SAFETY__HOLES__BEDROOM",
  "BUILDING_AND_SAFETY__HOLES__KITCHEN",
  "BUILDING_AND_SAFETY__BROKEN_LOCKS__BEDROOM",
  "BUILDING_AND_SAFETY__BROKEN_LOCKS__KITCHEN"
];

const LaIssueChoiceSet: Set<String> = new Set(LaIssueChoices);

export function isLaIssueChoice(choice: string): choice is LaIssueChoice {
  return LaIssueChoiceSet.has(choice);
}

export type LaIssueChoiceLabels = {
  [k in LaIssueChoice]: string;
};

export function getLaIssueChoiceLabels(): LaIssueChoiceLabels {
  return {
    HEALTH__MOLD__BEDROOM: li18n._(t`Mold`),
    HEALTH__MOLD__KITCHEN: li18n._(t`Mold`),
    HEALTH__PEELING_PAINT__BEDROOM: li18n._(t`Peeling paint`),
    HEALTH__PEELING_PAINT__KITCHEN: li18n._(t`Peeling paint`),
    HEALTH__RODENT_INFESTATION__BEDROOM: li18n._(t`Rodent infestation`),
    HEALTH__RODENT_INFESTATION__KITCHEN: li18n._(t`Rodent infestation`),
    UTILITIES__DEFECTIVE_ELECTRICITY__BEDROOM: li18n._(t`Defective electricity`),
    UTILITIES__DEFECTIVE_ELECTRICITY__KITCHEN: li18n._(t`Defective electricity`),
    UTILITIES__WATER_LEAK__BEDROOM: li18n._(t`Water leak`),
    UTILITIES__WATER_LEAK__KITCHEN: li18n._(t`Water leak`),
    BUILDING_AND_SAFETY__HOLES__BEDROOM: li18n._(t`Holes`),
    BUILDING_AND_SAFETY__HOLES__KITCHEN: li18n._(t`Holes`),
    BUILDING_AND_SAFETY__BROKEN_LOCKS__BEDROOM: li18n._(t`Broken locks`),
    BUILDING_AND_SAFETY__BROKEN_LOCKS__KITCHEN: li18n._(t`Broken locks`),
  };
}
