// This file was auto-generated by commondatabuilder.
// Please don't edit it.

export type LaIssueRoomChoice = "BEDROOM"|"LIVING_ROOM"|"BATHROOM"|"DINING_ROOM"|"HALLWAY"|"KITCHEN"|"COMMON_AREAS";

export const LaIssueRoomChoices: LaIssueRoomChoice[] = [
  "BEDROOM",
  "LIVING_ROOM",
  "BATHROOM",
  "DINING_ROOM",
  "HALLWAY",
  "KITCHEN",
  "COMMON_AREAS"
];

const LaIssueRoomChoiceSet: Set<String> = new Set(LaIssueRoomChoices);

export function isLaIssueRoomChoice(choice: string): choice is LaIssueRoomChoice {
  return LaIssueRoomChoiceSet.has(choice);
}

export type LaIssueRoomChoiceLabels = {
  [k in LaIssueRoomChoice]: string;
};

export function getLaIssueRoomChoiceLabels(): LaIssueRoomChoiceLabels {
  return {
    BEDROOM: "Bedroom",
    LIVING_ROOM: "Living room",
    BATHROOM: "Bathroom",
    DINING_ROOM: "Dining room",
    HALLWAY: "Hallway",
    KITCHEN: "Kitchen",
    COMMON_AREAS: "Common areas",
  };
}
