// This file was auto-generated by commondatabuilder.
// Please don't edit it.

import { t } from "@lingui/macro";
import { li18n } from '../frontend/lib/i18n-lingui';

export type LaIssueAreaChoice = "HEALTH"|"UTILITIES"|"BUILDING_AND_SAFETY";

export const LaIssueAreaChoices: LaIssueAreaChoice[] = [
  "HEALTH",
  "UTILITIES",
  "BUILDING_AND_SAFETY"
];

const LaIssueAreaChoiceSet: Set<String> = new Set(LaIssueAreaChoices);

export function isLaIssueAreaChoice(choice: string): choice is LaIssueAreaChoice {
  return LaIssueAreaChoiceSet.has(choice);
}

export type LaIssueAreaChoiceLabels = {
  [k in LaIssueAreaChoice]: string;
};

export function getLaIssueAreaChoiceLabels(): LaIssueAreaChoiceLabels {
  return {
    HEALTH: li18n._(t`Health`),
    UTILITIES: li18n._(t`Utilities`),
    BUILDING_AND_SAFETY: li18n._(t`Building and safety`),
  };
}
