// This file was auto-generated by commondatabuilder.
// Please don't edit it.

import { t } from "@lingui/macro";
import { li18n } from '../frontend/lib/i18n-lingui';

export type LaIssueCategoryChoice = "HEALTH"|"UTILITIES"|"BUILDING_AND_SAFETY";

export const LaIssueCategoryChoices: LaIssueCategoryChoice[] = [
  "HEALTH",
  "UTILITIES",
  "BUILDING_AND_SAFETY"
];

const LaIssueCategoryChoiceSet: Set<String> = new Set(LaIssueCategoryChoices);

export function isLaIssueCategoryChoice(choice: string): choice is LaIssueCategoryChoice {
  return LaIssueCategoryChoiceSet.has(choice);
}

export type LaIssueCategoryChoiceLabels = {
  [k in LaIssueCategoryChoice]: string;
};

export function getLaIssueCategoryChoiceLabels(): LaIssueCategoryChoiceLabels {
  return {
    HEALTH: li18n._(t`Health`),
    UTILITIES: li18n._(t`Utilities`),
    BUILDING_AND_SAFETY: li18n._(t`Building and safety`),
  };
}
