// This file was auto-generated by commondatabuilder.
// Please don't edit it.

import { t } from "@lingui/macro";
import { li18n } from '../frontend/lib/i18n-lingui';

export type LaIssueRoomChoice = "BEDROOM"|"LIVING_ROOM"|"BATHROOM"|"DINING_ROOM"|"HALLWAY"|"KITCHEN"|"COMMON_AREAS";

export const LaIssueRoomChoices: LaIssueRoomChoice[] = [
  "BEDROOM",
  "LIVING_ROOM",
  "BATHROOM",
  "DINING_ROOM",
  "HALLWAY",
  "KITCHEN",
  "COMMON_AREAS"
];

const LaIssueRoomChoiceSet: Set<String> = new Set(LaIssueRoomChoices);

export function isLaIssueRoomChoice(choice: string): choice is LaIssueRoomChoice {
  return LaIssueRoomChoiceSet.has(choice);
}

export type LaIssueRoomChoiceLabels = {
  [k in LaIssueRoomChoice]: string;
};

export function getLaIssueRoomChoiceLabels(): LaIssueRoomChoiceLabels {
  return {
    BEDROOM: li18n._(t`Bedroom`),
    LIVING_ROOM: li18n._(t`Living room`),
    BATHROOM: li18n._(t`Bathroom`),
    DINING_ROOM: li18n._(t`Dining room`),
    HALLWAY: li18n._(t`Hallway`),
    KITCHEN: li18n._(t`Kitchen`),
    COMMON_AREAS: li18n._(t`Common areas`),
  };
}
