// This file was auto-generated by commondatabuilder.
// Please don't edit it.

export enum IssueAreaChoice {
  HOME = "HOME",
  BEDROOMS = "BEDROOMS",
  KITCHEN = "KITCHEN",
  LIVING_ROOM = "LIVING_ROOM",
  BATHROOMS = "BATHROOMS",
  PUBLIC_AREAS = "PUBLIC_AREAS",
}

export type IssueAreaChoiceLabels = {
  [k in IssueAreaChoice]: string;
};

export function getIssueAreaChoiceLabels(): IssueAreaChoiceLabels {
  return {
    HOME: "Entire home and hallways",
    BEDROOMS: "Bedrooms",
    KITCHEN: "Kitchen",
    LIVING_ROOM: "Living room",
    BATHROOMS: "Bathrooms",
    PUBLIC_AREAS: "Public areas",
  };
}
