// This file was auto-generated by commondatabuilder.
// Please don't edit it.

import { t } from "@lingui/macro";
import { li18n } from '../frontend/lib/i18n-lingui';

export type IssueAreaChoice = "HOME"|"BEDROOMS"|"KITCHEN"|"LIVING_ROOM"|"BATHROOMS"|"PUBLIC_AREAS";

export const IssueAreaChoices: IssueAreaChoice[] = [
  "HOME",
  "BEDROOMS",
  "KITCHEN",
  "LIVING_ROOM",
  "BATHROOMS",
  "PUBLIC_AREAS"
];

const IssueAreaChoiceSet: Set<String> = new Set(IssueAreaChoices);

export function isIssueAreaChoice(choice: string): choice is IssueAreaChoice {
  return IssueAreaChoiceSet.has(choice);
}

export type IssueAreaChoiceLabels = {
  [k in IssueAreaChoice]: string;
};

export function getIssueAreaChoiceLabels(): IssueAreaChoiceLabels {
  return {
    HOME: li18n._(t`Entire home and hallways`),
    BEDROOMS: li18n._(t`Bedrooms`),
    KITCHEN: li18n._(t`Kitchen`),
    LIVING_ROOM: li18n._(t`Living room`),
    BATHROOMS: li18n._(t`Bathrooms`),
    PUBLIC_AREAS: li18n._(t`Public areas`),
  };
}
