// This file was auto-generated by commondatabuilder.
// Please don't edit it.

export type LetterChoice = "HABITABILITY"|"CA_HARASSMENT"|"LA_HARASSMENT"|"PRIVACY";

export const LetterChoices: LetterChoice[] = [
  "HABITABILITY",
  "CA_HARASSMENT",
  "LA_HARASSMENT",
  "PRIVACY"
];

const LetterChoiceSet: Set<String> = new Set(LetterChoices);

export function isLetterChoice(choice: string): choice is LetterChoice {
  return LetterChoiceSet.has(choice);
}

export type LetterChoiceLabels = {
  [k in LetterChoice]: string;
};

export function getLetterChoiceLabels(): LetterChoiceLabels {
  return {
    HABITABILITY: "Habitability (CA)",
    CA_HARASSMENT: "Harassment (CA)",
    LA_HARASSMENT: "Harassment (LA City/TAHO)",
    PRIVACY: "Right to Privacy (CA)",
  };
}
