// This file was auto-generated by commondatabuilder.
// Please don't edit it.

import { t } from "@lingui/macro";
import { li18n } from '../frontend/lib/i18n-lingui';

export type LeaseChoice = "RENT_STABILIZED"|"MARKET_RATE"|"NYCHA"|"OTHER"|"NO_LEASE";

export const LeaseChoices: LeaseChoice[] = [
  "RENT_STABILIZED",
  "MARKET_RATE",
  "NYCHA",
  "OTHER",
  "NO_LEASE"
];

const LeaseChoiceSet: Set<String> = new Set(LeaseChoices);

export function isLeaseChoice(choice: string): choice is LeaseChoice {
  return LeaseChoiceSet.has(choice);
}

export type LeaseChoiceLabels = {
  [k in LeaseChoice]: string;
};

export function getLeaseChoiceLabels(): LeaseChoiceLabels {
  return {
    RENT_STABILIZED: li18n._(t`Rent Stabilized/Rent Controlled`),
    MARKET_RATE: li18n._(t`Market Rate`),
    NYCHA: li18n._(t`NYCHA Housing Development`),
    OTHER: li18n._(t`Other (Mitchell Lama, COOP/Condo, House, HUD, etc.)`),
    NO_LEASE: li18n._(t`I don't have a lease`),
  };
}
