// This file was auto-generated by commondatabuilder.
// Please don't edit it.

export type LeaseChoice = "RENT_STABILIZED"|"MARKET_RATE"|"NYCHA"|"OTHER"|"NOT_SURE"|"NO_LEASE";

export const LeaseChoices: LeaseChoice[] = [
  "RENT_STABILIZED",
  "MARKET_RATE",
  "NYCHA",
  "OTHER",
  "NOT_SURE",
  "NO_LEASE"
];

const LeaseChoiceSet: Set<String> = new Set(LeaseChoices);

export function isLeaseChoice(choice: string): choice is LeaseChoice {
  return LeaseChoiceSet.has(choice);
}

export type LeaseChoiceLabels = {
  [k in LeaseChoice]: string;
};

export function getLeaseChoiceLabels(): LeaseChoiceLabels {
  return {
    RENT_STABILIZED: "Rent Stabilized/Rent Controlled",
    MARKET_RATE: "Market Rate",
    NYCHA: "NYCHA Housing Development",
    OTHER: "Other (Mitchell Lama, COOP/Condo, House, HUD, etc.)",
    NOT_SURE: "I'm not sure",
    NO_LEASE: "I don't have a lease",
  };
}
