// This file was auto-generated by commondatabuilder.
// Please don't edit it.

export type LocaleChoice = "en"|"es";

export const LocaleChoices: LocaleChoice[] = [
  "en",
  "es"
];

const LocaleChoiceSet: Set<String> = new Set(LocaleChoices);

export function isLocaleChoice(choice: string): choice is LocaleChoice {
  return LocaleChoiceSet.has(choice);
}
