// This file was auto-generated by commondatabuilder.
// Please don't edit it.

import { t } from "@lingui/macro";
import { li18n } from '../frontend/lib/i18n-lingui';

export type SignupIntent = "LOC"|"HP"|"EHP"|"NORENT";

export const SignupIntents: SignupIntent[] = [
  "LOC",
  "HP",
  "EHP",
  "NORENT"
];

const SignupIntentSet: Set<String> = new Set(SignupIntents);

export function isSignupIntent(choice: string): choice is SignupIntent {
  return SignupIntentSet.has(choice);
}

export type SignupIntentLabels = {
  [k in SignupIntent]: string;
};

export function getSignupIntentLabels(): SignupIntentLabels {
  return {
    LOC: li18n._(t`Letter of Complaint`),
    HP: li18n._(t`HP Action`),
    EHP: li18n._(t`Emergency HP Action`),
    NORENT: li18n._(t`No rent letter`),
  };
}
