# Generated by Django 2.1 on 2018-09-11 22:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text="The date on which the user's dwelling will be accessible.")),
                ('user', models.ForeignKey(help_text='The user whose dwelling this access date this is for.', on_delete=django.db.models.deletion.CASCADE, related_name='access_dates', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='accessdate',
            unique_together={('user', 'date')},
        ),
    ]
