# Generated by Django 2.1 on 2018-09-12 17:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandlordDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="The landlord's name.", max_length=100)),
                ('address', models.CharField(help_text='The full mailing address for the landlord.', max_length=1000)),
                ('user', models.OneToOneField(help_text='The user whose landlord details this is for.', on_delete=django.db.models.deletion.CASCADE, related_name='landlord_details', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
