# Generated by Django 2.1 on 2018-09-26 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loc', '0004_auto_20180914_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='landlorddetails',
            name='is_looked_up',
            field=models.BooleanField(default=False, help_text='Whether the name and address was looked up automatically, or manually entered by the user.'),
        ),
        migrations.AddField(
            model_name='landlorddetails',
            name='lookup_date',
            field=models.DateField(help_text="When we last tried to look up the landlord's details.", null=True),
        ),
    ]
