# Generated by Django 2.1.2 on 2018-10-04 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loc', '0005_auto_20180926_0207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letterrequest',
            name='mail_choice',
            field=models.TextField(choices=[('WE_WILL_MAIL', 'Yes, have JustFix.nyc mail this letter for me.'), ('USER_WILL_MAIL', "No thanks, I'll mail it myself. (You'll get a link to a PDF on the next page.)")], help_text='How the letter of complaint will be mailed.', max_length=30),
        ),
    ]
