# Generated by Django 2.1.7 on 2019-02-13 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loc', '0007_auto_20181025_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landlorddetails',
            name='address',
            field=models.CharField(help_text='The full mailing address for the landlord.', max_length=1000),
        ),
        migrations.AlterField(
            model_name='landlorddetails',
            name='name',
            field=models.CharField(help_text="The landlord's name.", max_length=100, blank=True),
        ),
    ]
