# Generated by Django 2.1.7 on 2019-03-13 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loc', '0008_auto_20190213_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='letterrequest',
            name='html_content',
            field=models.TextField(blank=True, help_text='The HTML content of the letter at the time it was requested.'),
        ),
    ]
