# Generated by Django 2.1.8 on 2019-04-02 08:29

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loc', '0009_letterrequest_html_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='letterrequest',
            name='lob_letter_object',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='If the letter was sent via Lob, this is the JSON response of the API call that was made to send the letter, documented at https://lob.com/docs/python#letters.', null=True),
        ),
        migrations.AddField(
            model_name='letterrequest',
            name='usps_tracking_number',
            field=models.CharField(blank=True, help_text='The USPS tracking number for the mail that was sent.', max_length=30),
        ),
    ]
