# Generated by Django 2.1.8 on 2019-04-02 23:11

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loc', '0009_letterrequest_html_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='letterrequest',
            name='lob_letter_object',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='If the letter was sent via Lob, this is the JSON response of the API call that was made to send the letter, documented at https://lob.com/docs/python#letters.', null=True),
        ),
    ]
