# Generated by Django 2.1.8 on 2019-04-16 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loc', '0010_letterrequest_lob_letter_object'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letterrequest',
            name='mail_choice',
            field=models.TextField(choices=[('WE_WILL_MAIL', 'Yes, have JustFix.nyc mail this letter for me.'), ('USER_WILL_MAIL', "No thanks, I'll mail it myself.")], help_text='How the letter of complaint will be mailed.', max_length=30),
        ),
    ]
