# Generated by Django 2.1.8 on 2019-04-19 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loc', '0011_auto_20190416_0945'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddressDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address', models.CharField(help_text='This is the address represented as a single string. Sometimes we need to manually break it up into its constituent parts so it is easier for machines to understand, which is what all the other fields in this model are for.', max_length=1000, unique=True)),
                ('primary_line', models.CharField(blank=True, help_text='Usually the first line of the address, e.g. "150 Court Street"', max_length=255)),
                ('secondary_line', models.CharField(blank=True, help_text='Optional. Usually the second line of the address, e.g. "Suite 2"', max_length=255)),
                ('urbanization', models.CharField(blank=True, help_text='Optional. Only used for addresses in Puerto Rico.', max_length=80)),
                ('city', models.CharField(blank=True, help_text='The city of the address, e.g. "Brooklyn".', max_length=80)),
                ('state', models.CharField(blank=True, help_text='The two-letter state for the address, e.g. "NY".', max_length=2)),
                ('zip_code', models.CharField(blank=True, help_text='The zip code of the address, e.g. "11201" or "94107-2282".', max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Address details',
            },
        ),
    ]
