# Generated by Django 2.1.8 on 2019-06-05 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loc', '0012_addressdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='addressdetails',
            name='is_definitely_deliverable',
            field=models.BooleanField(default=False, help_text='If you know for certain that this address is deliverable, even if Lob thinks otherwise, check this box. This will manually override Lob\'s verification and force any letters sent to this address to be mailed, assuming you have configured your <a href="https://lob.com/resources/guides/general/verification-of-mailing-addresses" target="_blank" rel="noopener nofollow">Lob strictness settings</a> to \'Relaxed\'.', verbose_name="This address is definitely deliverable (manually override Lob's address verification)"),
        ),
        migrations.AddField(
            model_name='addressdetails',
            name='notes',
            field=models.TextField(blank=True, help_text='Notes about this address. In particular, if you had to override the deliverability of this address or change it in non-trivial ways, please add your rationale here.'),
        ),
    ]
