# Generated by Django 2.2.4 on 2019-11-12 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loc', '0013_auto_20190605_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='letterrequest',
            name='tracking_number',
            field=models.CharField(blank=True, help_text='The tracking number for the letter.', max_length=100),
        ),
    ]
