# Generated by Django 2.2.4 on 2019-11-18 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loc', '0015_letterrequest_letter_sent_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='letterrequest',
            name='rejection_reason',
            field=models.CharField(blank=True, choices=[('INCRIMINATION', 'Letter is potentially incriminating'), ('CHANGED_MIND', 'Tenant changed their mind'), ('OTHER', 'Other')], help_text="The reason we didn't mail the letter, if applicable.", max_length=100),
        ),
    ]
