# Generated by Django 2.2.10 on 2020-03-31 20:23

from django.db import migrations, models
import project.util.phone_number


class Migration(migrations.Migration):

    dependencies = [
        ('loc', '0017_auto_20200212_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='landlorddetails',
            name='email',
            field=models.EmailField(blank=True, help_text="The landlord's email address.", max_length=254),
        ),
        migrations.AddField(
            model_name='landlorddetails',
            name='phone_number',
            field=models.CharField(blank=True, help_text='A U.S. phone number without parentheses or hyphens, e.g. "5551234567".', max_length=10, validators=[project.util.phone_number.validate_phone_number]),
        ),
    ]
