# Generated by Django 2.2.10 on 2020-04-22 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loc', '0021_auto_20200404_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landlorddetails',
            name='address',
            field=models.CharField(blank=True, help_text='The full mailing address for the landlord. This is a LEGACY field that we prefer not to use if possible, e.g. if the more granular primary/secondary line and city/state/zip details are available on this model.', max_length=1000, verbose_name='LEGACY address'),
        ),
    ]
