# Generated by Django 2.2.10 on 2020-05-02 12:21

from django.db import migrations
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_justfixuser_is_email_verified'),
        ('loc', '0022_auto_20200422_1555'),
    ]

    operations = [
        migrations.CreateModel(
            name='LOCUser',
            fields=[
            ],
            options={
                'verbose_name': 'User with Letter of Complaint',
                'verbose_name_plural': 'Users with Letters of Complaint',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.justfixuser',),
            managers=[
                ('objects', users.models.JustfixUserManager()),
            ],
        ),
    ]
