# Generated by Django 3.2.13 on 2023-07-26 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loc', '0027_auto_20210412_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivedletterrequest',
            name='mail_choice',
            field=models.TextField(choices=[('WE_WILL_MAIL', 'Yes, have JustFix mail this letter for me.'), ('USER_WILL_MAIL', "No thanks, I'll mail it myself.")], help_text='How the letter of complaint will be mailed.', max_length=30),
        ),
        migrations.AlterField(
            model_name='letterrequest',
            name='mail_choice',
            field=models.TextField(choices=[('WE_WILL_MAIL', 'Yes, have JustFix mail this letter for me.'), ('USER_WILL_MAIL', "No thanks, I'll mail it myself.")], help_text='How the letter of complaint will be mailed.', max_length=30),
        ),
    ]
