# Generated by Django 3.2.13 on 2025-01-02 17:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loc', '0028_auto_20241212_0311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='user',
            field=models.ForeignKey(help_text='The user whose home the work order tickets are for.', on_delete=django.db.models.deletion.CASCADE, related_name='work_order', to=settings.AUTH_USER_MODEL),
        ),
    ]
