from twofactor.models import TwofactorInfo
from .factories import TwofactorInfoFactory


def test_secret_is_autogenerated():
    tf = TwofactorInfo()
    assert len(tf.secret) == 16


def test_provisioning_uri_works(db):
    tf = TwofactorInfoFactory()
    assert (
        tf.provisioning_uri
        == "otpauth://totp/example.com:Boop%20Jones?secret=AAAAAAAAAAAAAAAA&issuer=example.com"
    )
