# Generated by Django 2.1.7 on 2019-03-22 14:05

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneNumberLookup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(help_text='A U.S. phone number without parentheses or hyphens, e.g. "5551234567".', max_length=10, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_valid', models.BooleanField(help_text='Whether Twilio thinks the phone number is valid.')),
                ('carrier', django.contrib.postgres.fields.jsonb.JSONField(default=None, help_text='Carrier information about the phone number. This is in the format specified in <a href="https://www.twilio.com/docs/lookup/api#lookups-carrier-info">Twilio\'s carrier information documentation</a>, though the keys are in snake-case rather than camel-case. This can be None if carrier info has not been looked up.', null=True)),
            ],
        ),
    ]
