# Generated by Django 3.2 on 2021-04-12 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texting', '0005_auto_20210202_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonenumberlookup',
            name='carrier',
            field=models.JSONField(default=None, help_text='Carrier information about the phone number. This is in the format specified in <a href="https://www.twilio.com/docs/lookup/api#lookups-carrier-info">Twilio\'s carrier information documentation</a>, though the keys are in snake-case rather than camel-case. This can be None if carrier info has not been looked up.', null=True),
        ),
    ]
