# Generated by Django 3.2 on 2021-05-10 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texting', '0006_alter_phonenumberlookup_carrier'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonenumberlookup',
            name='twilio_err_code',
            field=models.IntegerField(blank=True, choices=[(21211, 'invalid'), (21610, 'blocked')], help_text='If we think the phone number is invalid, this is the Twilio error code that underlies our reasoning.', null=True),
        ),
        migrations.AlterField(
            model_name='phonenumberlookup',
            name='is_valid',
            field=models.BooleanField(help_text='Whether we think the phone number is valid for the purposes of sending SMS numbers to it.'),
        ),
    ]
