# Generated by Django 3.2 on 2021-05-21 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texting', '0006_alter_phonenumberlookup_carrier'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='err_code',
            field=models.IntegerField(blank=True, help_text='The Twilio error code encountered when we last attempted to send the reminder, if any.', null=True),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='kind',
            field=models.TextField(choices=[('LOC', 'Letter of complaint reminder'), ('NORENT_CA_2020_11', 'NoRent California reminder - November 2020'), ('NORENT_CA_2020_12', 'NoRent California reminder - December 2020'), ('NORENT_CA_2021_01', 'NoRent California reminder - January 2021'), ('NORENT_CA_2021_02', 'NoRent California reminder - February 2021'), ('NORENT_CA_2021_03', 'NoRent California reminder - March 2021'), ('NORENT_CA_2021_04', 'NoRent California reminder - April 2021'), ('NORENT_CA_2021_05', 'NoRent California reminder - May 2021'), ('NORENT_CA_2021_06', 'NoRent California reminder - June 2021')], help_text='The type of reminder we attempted to send.', max_length=30),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='sent_at',
            field=models.DateField(help_text='When we last attempted to send the reminder.'),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='sid',
            field=models.CharField(blank=True, help_text='The Twilio Message SID for the reminder, if we sent it.', max_length=34),
        ),
    ]
