# Generated by Django 3.2.4 on 2021-08-03 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("texting", "0007_reminder_err_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reminder",
            name="kind",
            field=models.TextField(
                choices=[
                    ("LOC", "Letter of complaint reminder"),
                    ("NORENT_CA_2020_11", "NoRent California reminder - November 2020"),
                    ("NORENT_CA_2020_12", "NoRent California reminder - December 2020"),
                    ("NORENT_CA_2021_01", "NoRent California reminder - January 2021"),
                    ("NORENT_CA_2021_02", "NoRent California reminder - February 2021"),
                    ("NORENT_CA_2021_03", "NoRent California reminder - March 2021"),
                    ("NORENT_CA_2021_04", "NoRent California reminder - April 2021"),
                    ("NORENT_CA_2021_05", "NoRent California reminder - May 2021"),
                    ("NORENT_CA_2021_06", "NoRent California reminder - June 2021"),
                    ("NORENT_CA_2021_07", "NoRent California reminder - July 2021"),
                    ("NORENT_CA_2021_08", "NoRent California reminder - August 2021"),
                    ("NORENT_CA_2021_09", "NoRent California reminder - September 2021"),
                ],
                help_text="The type of reminder we attempted to send.",
                max_length=30,
            ),
        ),
    ]
