name: Boop

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  PIPENV_VENV_IN_PROJECT: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/Checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install pipenv
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          python --version
      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: .venv
          key: ${{ runner.os }}-pipenv-${{ hashFiles('Pipfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pipenv-
            ${{ runner.os }}-
      - name: Install dependencies
        run: |
          pipenv sync --dev --python 3.8
          ls -al
