name: Boop

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  PIPENV_VENV_IN_PROJECT: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/Checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8.2
      - name: Install pipenv
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          python --version
      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ~/.cache/pipenv
          key: ${{ runner.os }}-pipenv_cache-${{ hashFiles('Pipfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pipenv_cache-
            ${{ runner.os }}-
      - name: Install dependencies
        run: |
          pipenv sync --dev
      - name: Run flake8
        run: |
          pipenv run flake8
      - name: Run mypy
        run: |
          pipenv run mypy .
